variables:
  NUGET_PATH: 'C:\Tools\Nuget\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe'
  7ZIP_PATH: 'C:\Program Files\7-Zip\7z.exe'
  
stages:
  - build
  - deploy
  
build_job:
  stage: build
  only:
    - branches
    - /^(\d+\.)?(\d+\.)?(\d+.)?(\d+)$/
  script:
    - '& "$env:NUGET_PATH" restore OLS.Casy.sln'
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release /clp:ErrorsOnly OLS.Casy.sln'
  artifacts:
    expire_in: 2 days
    paths:
      - '.\BuildOutput\Release\'
      
deploy_job:
  stage: deploy
  only:
    - /^(\d+\.)?(\d+\.)?(\d+.)?(\d+)$/
  script:
    - echo $CI_BUILD_TAG
    - echo $CI_COMMIT_TAG
    - echo $CI_COMMIT_BRANCH
    - If(Test-Path .\Deployment) { Remove-Item -Recurse -Force .\Deployment }
    - New-Item -ItemType directory -Path .\Deployment\$CI_COMMIT_BRANCH
    - cd .\Deployment\$CI_COMMIT_BRANCH
    - New-Item -ItemType directory -Path .\access
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Core.Authorization.Access.dll' -Destination '.\access'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Ui.Authorization.Access.dll' -Destination '.\access'
    - cd .\access
    - '& "$env:7ZIP_PATH" a -mx=9 "access.zip" "."'
    - Copy-Item '.\access.zip' -Destination '..'
    - cd ..
    - New-Item -ItemType directory -Path .\adAuth
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Authorization.ActiveDirectory.SetGroupsUtil.exe' -Destination '.\adAuth'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Authorization.ActiveDirectory.SetGroupsUtil.exe.config' -Destination '.\adAuth'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Core.Authorization.ActiveDirectory.dll' -Destination '.\adAuth'
    - cd .\adAuth
    - '& "$env:7ZIP_PATH" a -mx=9 "adAuth.zip" "."'
    - Copy-Item '.\adAuth.zip' -Destination '..'
    - cd ..
    - New-Item -ItemType directory -Path .\cfr
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.IO.SQLite.EF.AuditTrail.dll' -Destination '.\cfr'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.IO.SQLite.EF.Standard.AuditTrail.dll' -Destination '.\cfr'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Ui.AuditTrail.dll' -Destination '.\cfr'
    - cd .\cfr
    - '& "$env:7ZIP_PATH" a -mx=9 "cfr.zip" "."'
    - Copy-Item '.\cfr.zip' -Destination '..'
    - cd ..
    - New-Item -ItemType directory -Path .\control
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Com.dll' -Destination '.\control'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Controller.Calibration.dll' -Destination '.\control'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Controller.Error.dll' -Destination '.\control'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Controller.Service.dll' -Destination '.\control'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Ui.Measure.dll' -Destination '.\control'
    - cd .\control
    - '& "$env:7ZIP_PATH" a -mx=9 "control.zip" "."'
    - Copy-Item '.\control.zip' -Destination '..'
    - cd ..
    - New-Item -ItemType directory -Path .\counter
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Controller.MC.dll' -Destination '.\counter'
    - cd .\counter
    - '& "$env:7ZIP_PATH" a -mx=9 "counter.zip" "."'
    - Copy-Item '.\counter.zip' -Destination '..'
    - cd ..
    - New-Item -ItemType directory -Path .\localAuth
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Core.Authorization.Local.dll' -Destination '.\localAuth'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Ui.Authorization.dll' -Destination '.\localAuth'
    - cd .\localAuth
    - '& "$env:7ZIP_PATH" a -mx=9 "localAuth.zip" "."'
    - Copy-Item '.\localAuth.zip' -Destination '..'
    - cd ..
    - New-Item -ItemType directory -Path .\main
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Charts.v16.2.Core.dll' -Destination '.\main'
    #- Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.CodeParser.v16.2.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Data.v16.2.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Data.v16.2.xml' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Mvvm.v16.2.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Mvvm.v16.2.xml' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Office.v16.2.Core.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Office.v16.2.Core.xml' -Destination '.\main'
    #- Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Pdf.v16.2.Core.dll' -Destination '.\main'
    #- Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Pdf.v16.2.Core.xml' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Printing.v16.2.Core.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Printing.v16.2.Core.xml' -Destination '.\main'
    #- Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.RichEdit.v16.2.Core.dll' -Destination '.\main'
    #- Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.RichEdit.v16.2.Core.xml' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Xpf.Charts.v16.2.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Xpf.Charts.v16.2.xml' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Xpf.Core.v16.2.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Xpf.Core.v16.2.xml' -Destination '.\main'
    #- Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Xpf.Docking.v16.2.dll' -Destination '.\main'
    #- Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Xpf.Docking.v16.2.xml' -Destination '.\main'
    #- Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Xpf.DocumentViewer.v16.2.Core.dll' -Destination '.\main'
    #- Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Xpf.DocumentViewer.v16.2.Core.xml' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Xpf.Grid.v16.2.Core.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Xpf.Grid.v16.2.Core.xml' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Xpf.Grid.v16.2.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Xpf.Grid.v16.2.xml' -Destination '.\main'
    #- Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Xpf.Layout.v16.2.Core.dll' -Destination '.\main'
    #- Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Xpf.Layout.v16.2.Core.xml' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Xpf.Printing.v16.2.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Xpf.Printing.v16.2.xml' -Destination '.\main'
    #- Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Xpf.Ribbon.v16.2.dll' -Destination '.\main'
    #- Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Xpf.Ribbon.v16.2.xml' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\DevExpress.Xpf.Themes.Office2016White.v16.2.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\EntityFramework.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\EntityFramework.SqlServer.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\EPPlus.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\log4net.config' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\Microsoft.Extensions.DependencyInjection.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\Microsoft.Extensions.Logging.Debug.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\Microsoft.Extensions.Logging.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\Microsoft.Extensions.Options.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.AppService.exe' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Base.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Calculation.Api.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Calculation.Normalization.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Calculation.PolynomialFitting.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Calculation.Smooth.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Calculation.Volume.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Com.Api.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Controller.Api.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Controller.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Controller.Measure.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Core.Activation.Model.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Core.Api.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Core.Authorization.Api.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Core.Authorization.Default.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Core.Authorization.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Core.Authorization.Emergency.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Core.Authorization.Encryption.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Core.Config.Api.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Core.Config.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Core.Detection.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Core.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Core.Events.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Core.Localization.Api.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Core.Localization.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Core.Logging.Api.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Core.Logging.SQLite.EF.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Core.Notification.Api.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Core.Notification.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Core.Runtime.Api.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Core.Runtime.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Core.Ui.Workflow.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Core.Update.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Core.Update.Ui.exe' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Core.Update.Ui.exe.config' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.ErrorReport.Ui.exe' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.ErrorReport.Ui.exe.config' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.IO.Api.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.IO.Backup.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.IO.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.IO.ImportExport.Binary.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.IO.ImportExport.CRF.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.IO.ImportExport.Raw.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.IO.ImportExport.TT.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.IO.SQLite.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.IO.SQLite.EF.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.IO.SQLite.Standard.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.IO.UsbDetection.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Models.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Monitoring.Api.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Monitoring.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.RemoteIPS.Api.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Ui.Analyze.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Ui.Api.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Ui.Authorization.Api.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Ui.Base.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Ui.Core.Api.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Ui.Core.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Ui.Core.TipTap.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Ui.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Ui.MainControls.Api.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Ui.MainControls.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\Remotion.Linq.dll' -Destination '.\main'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\System.Drawing.Common.dll' -Destination '.\main'
    #- Copy-Item '..\..\BuildOutput\Release\Casy\net472\System.Net.Http.WebRequest.dll' -Destination '.\main'
    - Set-Content -Path '.\main\version' -Value $CI_COMMIT_BRANCH
    - cd .\main
    - '& "$env:7ZIP_PATH" a -mx=9 "main.zip" "."'
    - Copy-Item '.\main.zip' -Destination '..'
    - cd ..
    - New-Item -ItemType directory -Path .\simulator
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Com.Simulation.dll' -Destination '.\simulator'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Controller.Calibration.dll' -Destination '.\simulator'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Controller.Error.dll' -Destination '.\simulator'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Controller.Service.dll' -Destination '.\simulator'
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Ui.Measure.dll' -Destination '.\simulator'
    - cd .\simulator
    - '& "$env:7ZIP_PATH" a -mx=9 "simulator.zip" "."'
    - Copy-Item '.\simulator.zip' -Destination '..'
    - cd ..
    - New-Item -ItemType directory -Path .\tipTap
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Ui.Core.TipTap.dll' -Destination '.\tipTap'
    - cd .\tipTap
    - '& "$env:7ZIP_PATH" a -mx=9 "tipTap.zip" "."'
    - Copy-Item '.\tipTap.zip' -Destination '..'
    - cd ..
    - New-Item -ItemType directory -Path .\trial
    - Copy-Item '..\..\BuildOutput\Release\Casy\net472\OLS.Casy.Core.Sync.dll' -Destination '.\trial'
    - cd .\trial
    - '& "$env:7ZIP_PATH" a -mx=9 "trial.zip" "."'
    - Copy-Item '.\trial.zip' -Destination '..'
    - cd ..
    - New-Item -ItemType directory -Path .\ttSwitch
    - Copy-Item '..\..\BuildOutput\Release\Casy\netstandard2.0\OLS.Casy.Com.TTSwitch.dll' -Destination '.\ttSwitch'
    - cd .\ttSwitch
    - '& "$env:7ZIP_PATH" a -mx=9 "ttSwitch.zip" "."'
    - Copy-Item '.\ttSwitch.zip' -Destination '..'
    - cd ..
  dependencies:
    - build_job