variables:
  NUGET_PATH: 'C:\Tools\Nuget\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe'
  
stages:
  - build
  - deploy
  
build_job:
  stage: build
  only:
    - branches
  script:
    - '& "$env:NUGET_PATH" restore OLS.Casy.sln'
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release /clp:ErrorsOnly OLS.Casy.sln'
  artifacts:
    expire_in: 2 days
    paths:
      - '.\BuildOutput\Release\'
      
deploy_job:
  stage: deploy
  only:
    - tags
    #- /^(\d+\.)?(\d+\.)?(\d+)$/
  script:
    - echo $CI_BUILD_TAG