//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLS.Casy.Ui.Analyze.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings_de_DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLS.Casy.Ui.Analyze.Assets.Resources.ApplicationStrings_de-DE", typeof(ApplicationStrings_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die ausgewählten Messungen sind für eine Mittelwertanzeige inkompatibel.
        ///Die folgenden Eigenschaften unterscheiden sich:
        ///{0} ähnelt.
        /// </summary>
        internal static string AnalyzeMeanChartViewModel_InvalidSelectedMeasurementResult_Message {
            get {
                return ResourceManager.GetString("AnalyzeMeanChartViewModel_InvalidSelectedMeasurementResult_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mittelwert-Anzeige nicht möglich ähnelt.
        /// </summary>
        internal static string AnalyzeMeanChartViewModel_InvalidSelectedMeasurementResult_Title {
            get {
                return ResourceManager.GetString("AnalyzeMeanChartViewModel_InvalidSelectedMeasurementResult_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ZOOM ähnelt.
        /// </summary>
        internal static string AnalyzeMultipleChatsView_Zoom_Label {
            get {
                return ResourceManager.GetString("AnalyzeMultipleChatsView_Zoom_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die ausgewählten Messungen sind für ein Overlay inkompatibel.
        ///Die folgenden Eigenschaften unterscheiden sich:
        ///{0} ähnelt.
        /// </summary>
        internal static string AnalyzeOverlayChartViewModel_InvalidSelectedMeasurementResult_Message {
            get {
                return ResourceManager.GetString("AnalyzeOverlayChartViewModel_InvalidSelectedMeasurementResult_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overlay-Anzeige nicht möglich ähnelt.
        /// </summary>
        internal static string AnalyzeOverlayChartViewModel_InvalidSelectedMeasurementResult_Title {
            get {
                return ResourceManager.GetString("AnalyzeOverlayChartViewModel_InvalidSelectedMeasurementResult_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aggr. Berech. Modus ähnelt.
        /// </summary>
        internal static string AnnotationType_AggregationCalculationMode_Header {
            get {
                return ResourceManager.GetString("AnnotationType_AggregationCalculationMode_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kapillare ähnelt.
        /// </summary>
        internal static string AnnotationType_CapillarySize_Header {
            get {
                return ResourceManager.GetString("AnnotationType_CapillarySize_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum Messung ähnelt.
        /// </summary>
        internal static string AnnotationType_CreatedAt_Header {
            get {
                return ResourceManager.GetString("AnnotationType_CreatedAt_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ersteller ähnelt.
        /// </summary>
        internal static string AnnotationType_CreatedBy_Header {
            get {
                return ResourceManager.GetString("AnnotationType_CreatedBy_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verdünnungsfaktor ähnelt.
        /// </summary>
        internal static string AnnotationType_DilutionFactor_Header {
            get {
                return ResourceManager.GetString("AnnotationType_DilutionFactor_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Min Durchmesser (X-Achse) ähnelt.
        /// </summary>
        internal static string AnnotationType_FromDiameter_Header {
            get {
                return ResourceManager.GetString("AnnotationType_FromDiameter_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Letzter Modifikator ähnelt.
        /// </summary>
        internal static string AnnotationType_LastModifiedAt_Header {
            get {
                return ResourceManager.GetString("AnnotationType_LastModifiedAt_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zuletzt Modifiziert ähnelt.
        /// </summary>
        internal static string AnnotationType_LastModifiedBy_Header {
            get {
                return ResourceManager.GetString("AnnotationType_LastModifiedBy_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Man. Aggr. Faktor ähnelt.
        /// </summary>
        internal static string AnnotationType_ManualAggregationCalculationFactor_Header {
            get {
                return ResourceManager.GetString("AnnotationType_ManualAggregationCalculationFactor_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messdatum ähnelt.
        /// </summary>
        internal static string AnnotationType_MeasuredAt_Header {
            get {
                return ResourceManager.GetString("AnnotationType_MeasuredAt_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messmethode ähnelt.
        /// </summary>
        internal static string AnnotationType_MeasureMode_Header {
            get {
                return ResourceManager.GetString("AnnotationType_MeasureMode_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zyklen ähnelt.
        /// </summary>
        internal static string AnnotationType_Repeats_Header {
            get {
                return ResourceManager.GetString("AnnotationType_Repeats_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max Wert Y-Achse ähnelt.
        /// </summary>
        internal static string AnnotationType_ScalingMaxRange_Header {
            get {
                return ResourceManager.GetString("AnnotationType_ScalingMaxRange_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modus Y-Achse ähnelt.
        /// </summary>
        internal static string AnnotationType_ScalingMode_Header {
            get {
                return ResourceManager.GetString("AnnotationType_ScalingMode_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Glättungsfaktor ähnelt.
        /// </summary>
        internal static string AnnotationType_SmoothingFactor_Header {
            get {
                return ResourceManager.GetString("AnnotationType_SmoothingFactor_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorlagenname ähnelt.
        /// </summary>
        internal static string AnnotationType_TemplateName_Header {
            get {
                return ResourceManager.GetString("AnnotationType_TemplateName_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max Durchmesser (X-Achse) ähnelt.
        /// </summary>
        internal static string AnnotationType_ToDiameter_Header {
            get {
                return ResourceManager.GetString("AnnotationType_ToDiameter_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einheit Y-Achse ähnelt.
        /// </summary>
        internal static string AnnotationType_UnitMode_Header {
            get {
                return ResourceManager.GetString("AnnotationType_UnitMode_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messvolumen ähnelt.
        /// </summary>
        internal static string AnnotationType_Volume_Header {
            get {
                return ResourceManager.GetString("AnnotationType_Volume_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mittelwert Ergebnis ähnelt.
        /// </summary>
        internal static string MeanMeasureResult_Name {
            get {
                return ResourceManager.GetString("MeanMeasureResult_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        /// </summary>
        internal static string MeasureResult_Concentration_Ok {
            get {
                return ResourceManager.GetString("MeasureResult_Concentration_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zu hoch ähnelt.
        /// </summary>
        internal static string MeasureResult_Concentration_TooHigh {
            get {
                return ResourceManager.GetString("MeasureResult_Concentration_TooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die weitere Metadaten-Spalten ähnelt.
        /// </summary>
        internal static string MeasureResultTableView_AdditinalColumns_Header {
            get {
                return ResourceManager.GetString("MeasureResultTableView_AdditinalColumns_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Annotationen ähnelt.
        /// </summary>
        internal static string MeasureResultTableView_Category_Annotation {
            get {
                return ResourceManager.GetString("MeasureResultTableView_Category_Annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allgemein ähnelt.
        /// </summary>
        internal static string MeasureResultTableView_Category_General {
            get {
                return ResourceManager.GetString("MeasureResultTableView_Category_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subpopulationen ähnelt.
        /// </summary>
        internal static string MeasureResultTableView_Category_Subpopulation {
            get {
                return ResourceManager.GetString("MeasureResultTableView_Category_Subpopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auswahl zurücksetzen ähnelt.
        /// </summary>
        internal static string MeasureResultTableView_ClearSelection {
            get {
                return ResourceManager.GetString("MeasureResultTableView_ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selektierte Messungen löschen ähnelt.
        /// </summary>
        internal static string MeasureResultTableView_DeleteButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultTableView_DeleteButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selektierte Messungen exportieren ähnelt.
        /// </summary>
        internal static string MeasureResultTableView_ExportButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultTableView_ExportButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string MeasureResultTableView_GridColumn_Name {
            get {
                return ResourceManager.GetString("MeasureResultTableView_GridColumn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorauswahl: ähnelt.
        /// </summary>
        internal static string MeasureResultTableView_Presets_Label {
            get {
                return ResourceManager.GetString("MeasureResultTableView_Presets_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tabellenansicht drucken ähnelt.
        /// </summary>
        internal static string MeasureResultTableView_PrintButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultTableView_PrintButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auswahl speichern ähnelt.
        /// </summary>
        internal static string MeasureResultTableView_SaveSelection {
            get {
                return ResourceManager.GetString("MeasureResultTableView_SaveSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Experiment ähnelt.
        /// </summary>
        internal static string MeasureResultTebleView_GridColumn_Experiment {
            get {
                return ResourceManager.GetString("MeasureResultTebleView_GridColumn_Experiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gruppe ähnelt.
        /// </summary>
        internal static string MeasureResultTebleView_GridColumn_Group {
            get {
                return ResourceManager.GetString("MeasureResultTebleView_GridColumn_Group", resourceCulture);
            }
        }
    }
}
