//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLS.Casy.Controller.Error.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings_de_DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLS.Casy.Controller.Error.Assets.Resources.ApplicationStrings_de-DE", typeof(ApplicationStrings_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeitüberschreitung der Messung.
        ///Kapillare möglicherweise verstopft. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0001_Description {
            get {
                return ResourceManager.GetString("Error_0000_0000_0001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0001_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0000_0001_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zum Bestätigen &apos;ENTER&apos; drücken.
        ///Drücken Sie &apos;CLEAN&apos; um das Flüssigkeitssystem zu reinigen. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0001_Information {
            get {
                return ResourceManager.GetString("Error_0000_0000_0001_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wird empfohlen CASYclean regelmäßig zu verwenden!
        ///
        ///Wechsle das CASYcup zu einem mit CASYton gefüllten und versuche eine SPÜLEN um die Blockade zu entfernen.. 
        ///WIEDERHOLEN starte einen neuen Messzyklus.
        ///Sollte das Problem weiterhin bestehen, führe den &quot;Kapillare reinigen Wizard&quot; im Servicemenü aus. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0001_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0000_0001_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeitüberschreitung der Messung.
        ///Kapillare möglicherweise verstopft. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0002_Description {
            get {
                return ResourceManager.GetString("Error_0000_0000_0002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0002_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0000_0002_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM
        ///PRESS CLEAN TO FLUSH THE LIQUID SYSTEM ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0002_Information {
            get {
                return ResourceManager.GetString("Error_0000_0000_0002_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wird empfohlen CASYclean regelmäßig zu verwenden!
        ///
        ///Wechsle das CASYcup zu einem mit CASYton gefüllten und versuche eine SPÜLEN um die Blockade zu entfernen.. 
        ///WIEDERHOLEN starte einen neuen Messzyklus.
        ///Sollte das Problem weiterhin bestehen, führe den &quot;Kapillare reinigen Wizard&quot; im Servicemenü aus. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0002_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0000_0002_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Große Luftblase entdeckt. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0004_Description {
            get {
                return ResourceManager.GetString("Error_0000_0000_0004_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0004_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0000_0004_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM 
        ///PRESS CLEAN TO FLUSH THE LIQUID SYSTEM ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0004_Information {
            get {
                return ResourceManager.GetString("Error_0000_0000_0004_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wird empfohlen CASYclean regelmäßig zu verwenden!
        ///Weitere Informationen erhalten Sie in der Gebrauchsanweisung. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0004_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0000_0004_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Große Luftblase entdeckt. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0008_Description {
            get {
                return ResourceManager.GetString("Error_0000_0000_0008_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0008_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0000_0008_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM
        ///PRESS CLEAN TO FLUSH THE LIQUID SYSTEM ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0008_Information {
            get {
                return ResourceManager.GetString("Error_0000_0000_0008_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wird empfohlen CASYclean regelmäßig zu verwenden!
        ///Weitere Informationen erhalten Sie in der Gebrauchsanweisung. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0008_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0000_0008_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konzentration zu hoch. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0010_Description {
            get {
                return ResourceManager.GetString("Error_0000_0000_0010_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0010_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0000_0010_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM
        ///PRESS CLEAN TO FLUSH THE LIQUID SYSTEM ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0010_Information {
            get {
                return ResourceManager.GetString("Error_0000_0000_0010_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte verdünnen Sie ihre Probe.
        ///Weitere Informationen erhalten Sie in der Gebrauchsanweisung. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0010_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0000_0010_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Messung wurde durch den Benutzer unterbrochen. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0020_Description {
            get {
                return ResourceManager.GetString("Error_0000_0000_0020_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0020_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0000_0020_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0020_Information {
            get {
                return ResourceManager.GetString("Error_0000_0000_0020_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte verdünnen Sie ihre Probe.
        ///Weitere Informationen erhalten Sie in der Gebrauchsanweisung. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0020_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0000_0020_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Reinigung wurde durch den Benutzer unterbrochen. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0040_Description {
            get {
                return ResourceManager.GetString("Error_0000_0000_0040_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0040_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0000_0040_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0040_Information {
            get {
                return ResourceManager.GetString("Error_0000_0000_0040_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0040_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0000_0040_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0080_Description {
            get {
                return ResourceManager.GetString("Error_0000_0000_0080_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0080_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0000_0080_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0080_Information {
            get {
                return ResourceManager.GetString("Error_0000_0000_0080_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0080_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0000_0080_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0100_Description {
            get {
                return ResourceManager.GetString("Error_0000_0000_0100_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HW-1a ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0100_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0000_0100_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0100_Information {
            get {
                return ResourceManager.GetString("Error_0000_0000_0100_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schalten Sie ihr CASY für mindestens 5 Sekunden aus.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0100_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0000_0100_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0200_Description {
            get {
                return ResourceManager.GetString("Error_0000_0000_0200_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HW-1b ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0200_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0000_0200_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0200_Information {
            get {
                return ResourceManager.GetString("Error_0000_0000_0200_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schalten Sie ihr CASY für mindestens 5 Sekunden aus.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0200_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0000_0200_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0400_Description {
            get {
                return ResourceManager.GetString("Error_0000_0000_0400_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HW-2a ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0400_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0000_0400_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0400_Information {
            get {
                return ResourceManager.GetString("Error_0000_0000_0400_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schalten Sie ihr CASY für mindestens 5 Sekunden aus.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0400_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0000_0400_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0800_Description {
            get {
                return ResourceManager.GetString("Error_0000_0000_0800_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HW-2b ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0800_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0000_0800_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0800_Information {
            get {
                return ResourceManager.GetString("Error_0000_0000_0800_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schalten Sie ihr CASY für mindestens 5 Sekunden aus.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_0800_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0000_0800_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Realtime Clock funktioniert nicht ähnelt.
        /// </summary>
        internal static string Error_0000_0000_1000_Description {
            get {
                return ResourceManager.GetString("Error_0000_0000_1000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HW-3a ähnelt.
        /// </summary>
        internal static string Error_0000_0000_1000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0000_1000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0000_0000_1000_Information {
            get {
                return ResourceManager.GetString("Error_0000_0000_1000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihr System wird weiterhin funktionieren, aber die Zeit und das Datum können falsch sein.
        ///Weitere Informationen erhalten Sie in der Gebrauchsanweisung. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_1000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0000_1000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Stromversorgung der Realtime Clock ist schwach ähnelt.
        /// </summary>
        internal static string Error_0000_0000_2000_Description {
            get {
                return ResourceManager.GetString("Error_0000_0000_2000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HW-3b ähnelt.
        /// </summary>
        internal static string Error_0000_0000_2000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0000_2000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0000_0000_2000_Information {
            get {
                return ResourceManager.GetString("Error_0000_0000_2000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihr System wird weiterhin funktionieren, aber die Zeit und das Datum können falsch sein.
        ///Weitere Informationen erhalten Sie in der Gebrauchsanweisung. ähnelt.
        /// </summary>
        internal static string Error_0000_0000_2000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0000_2000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_4000_Description {
            get {
                return ResourceManager.GetString("Error_0000_0000_4000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_4000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0000_4000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_4000_Information {
            get {
                return ResourceManager.GetString("Error_0000_0000_4000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_4000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0000_4000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_8000_Description {
            get {
                return ResourceManager.GetString("Error_0000_0000_8000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_8000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0000_8000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_8000_Information {
            get {
                return ResourceManager.GetString("Error_0000_0000_8000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0000_8000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0000_8000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0001_0000_Description {
            get {
                return ResourceManager.GetString("Error_0000_0001_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MM-1 ähnelt.
        /// </summary>
        internal static string Error_0000_0001_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0001_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0000_0001_0000_Information {
            get {
                return ResourceManager.GetString("Error_0000_0001_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schalten Sie ihr CASY für mindestens 5 Sekunden aus.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_0000_0001_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0001_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0002_0000_Description {
            get {
                return ResourceManager.GetString("Error_0000_0002_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MM-2 ähnelt.
        /// </summary>
        internal static string Error_0000_0002_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0002_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0000_0002_0000_Information {
            get {
                return ResourceManager.GetString("Error_0000_0002_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schalten Sie ihr CASY für mindestens 5 Sekunden aus.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_0000_0002_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0002_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0004_0000_Description {
            get {
                return ResourceManager.GetString("Error_0000_0004_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MM-3 ähnelt.
        /// </summary>
        internal static string Error_0000_0004_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0004_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0000_0004_0000_Information {
            get {
                return ResourceManager.GetString("Error_0000_0004_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schalten Sie ihr CASY für mindestens 5 Sekunden aus.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_0000_0004_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0004_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0008_0000_Description {
            get {
                return ResourceManager.GetString("Error_0000_0008_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MM-4 ähnelt.
        /// </summary>
        internal static string Error_0000_0008_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0008_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0000_0008_0000_Information {
            get {
                return ResourceManager.GetString("Error_0000_0008_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schalten Sie ihr CASY für mindestens 5 Sekunden aus.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_0000_0008_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0008_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0010_0000_Description {
            get {
                return ResourceManager.GetString("Error_0000_0010_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PR-1a ähnelt.
        /// </summary>
        internal static string Error_0000_0010_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0010_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0000_0010_0000_Information {
            get {
                return ResourceManager.GetString("Error_0000_0010_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schalten Sie ihr CASY für mindestens 5 Sekunden aus.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_0000_0010_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0010_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0020_0000_Description {
            get {
                return ResourceManager.GetString("Error_0000_0020_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PR-1b ähnelt.
        /// </summary>
        internal static string Error_0000_0020_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0020_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0000_0020_0000_Information {
            get {
                return ResourceManager.GetString("Error_0000_0020_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schalten Sie ihr CASY für mindestens 5 Sekunden aus.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_0000_0020_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0020_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0040_0000_Description {
            get {
                return ResourceManager.GetString("Error_0000_0040_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PR-2a ähnelt.
        /// </summary>
        internal static string Error_0000_0040_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0040_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0000_0040_0000_Information {
            get {
                return ResourceManager.GetString("Error_0000_0040_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schalten Sie ihr CASY für mindestens 5 Sekunden aus.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_0000_0040_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0040_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0080_0000_Description {
            get {
                return ResourceManager.GetString("Error_0000_0080_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PR-2b ähnelt.
        /// </summary>
        internal static string Error_0000_0080_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0080_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0000_0080_0000_Information {
            get {
                return ResourceManager.GetString("Error_0000_0080_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schalten Sie ihr CASY für mindestens 5 Sekunden aus.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_0000_0080_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0080_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0100_0000_Description {
            get {
                return ResourceManager.GetString("Error_0000_0100_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PR-3 ähnelt.
        /// </summary>
        internal static string Error_0000_0100_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0100_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0000_0100_0000_Information {
            get {
                return ResourceManager.GetString("Error_0000_0100_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schalten Sie ihr CASY für mindestens 5 Sekunden aus.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_0000_0100_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0100_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0200_0000_Description {
            get {
                return ResourceManager.GetString("Error_0000_0200_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PR-4 ähnelt.
        /// </summary>
        internal static string Error_0000_0200_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0200_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0000_0200_0000_Information {
            get {
                return ResourceManager.GetString("Error_0000_0200_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schalten Sie ihr CASY für mindestens 5 Sekunden aus.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_0000_0200_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0200_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Flüssigkeitssystem konnte nicht geleert werden. ähnelt.
        /// </summary>
        internal static string Error_0000_0400_0000_Description {
            get {
                return ResourceManager.GetString("Error_0000_0400_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PR-5 ähnelt.
        /// </summary>
        internal static string Error_0000_0400_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0400_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY
        ///PRESS CLEAN TO FLUSH THE LIQUID SYSTEM ähnelt.
        /// </summary>
        internal static string Error_0000_0400_0000_Information {
            get {
                return ResourceManager.GetString("Error_0000_0400_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte spülen Sie das Flüssigkeitssystem und versuchen es erneut.
        ///Weitere Informationen erhalten Sie in der Gebrauchsanweisung. ähnelt.
        /// </summary>
        internal static string Error_0000_0400_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0400_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_0800_0000_Description {
            get {
                return ResourceManager.GetString("Error_0000_0800_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PR-6 ähnelt.
        /// </summary>
        internal static string Error_0000_0800_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_0800_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY
        ///PRESS CLEAN TO FLUSH THE LIQUID SYSTEM ähnelt.
        /// </summary>
        internal static string Error_0000_0800_0000_Information {
            get {
                return ResourceManager.GetString("Error_0000_0800_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte spülen Sie das Flüssigkeitssystem und versuchen es erneut.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_0000_0800_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_0800_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Messzeit war zu kurz. ähnelt.
        /// </summary>
        internal static string Error_0000_1000_0000_Description {
            get {
                return ResourceManager.GetString("Error_0000_1000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PR-7 ähnelt.
        /// </summary>
        internal static string Error_0000_1000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_1000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY
        ///PRESS CLEAN TO FLUSH THE LIQUID SYSTEM ähnelt.
        /// </summary>
        internal static string Error_0000_1000_0000_Information {
            get {
                return ResourceManager.GetString("Error_0000_1000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte überprüfen Sie, ob Sie die richtige Kapillare installiert haben.
        ///Weitere Informationen erhalten Sie in der Gebrauchsanweisung. ähnelt.
        /// </summary>
        internal static string Error_0000_1000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_1000_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Flüssigkeitssystem konnte während der Reinigung nicht gefüllt werden. ähnelt.
        /// </summary>
        internal static string Error_0000_2000_0000_Description {
            get {
                return ResourceManager.GetString("Error_0000_2000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PR-8 ähnelt.
        /// </summary>
        internal static string Error_0000_2000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_2000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY
        ///PRESS CLEAN TO FLUSH THE LIQUID SYSTEM ähnelt.
        /// </summary>
        internal static string Error_0000_2000_0000_Information {
            get {
                return ResourceManager.GetString("Error_0000_2000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte überprüfen Sie, dass ausreichend CASYton im Aufbewahrungsbehälter vorhanden ist.
        ///Weitere Informationen erhalten Sie in der Gebrauchsanweisung. ähnelt.
        /// </summary>
        internal static string Error_0000_2000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_2000_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_4000_0000_Description {
            get {
                return ResourceManager.GetString("Error_0000_4000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_4000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_4000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_4000_0000_Information {
            get {
                return ResourceManager.GetString("Error_0000_4000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_4000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_4000_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_8000_0000_Description {
            get {
                return ResourceManager.GetString("Error_0000_8000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_8000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0000_8000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_8000_0000_Information {
            get {
                return ResourceManager.GetString("Error_0000_8000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0000_8000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0000_8000_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0001_0000_0000_Description {
            get {
                return ResourceManager.GetString("Error_0001_0000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SG-1a ähnelt.
        /// </summary>
        internal static string Error_0001_0000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0001_0000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0001_0000_0000_Information {
            get {
                return ResourceManager.GetString("Error_0001_0000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schalten Sie ihr CASY für mindestens 5 Sekunden aus.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_0001_0000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0001_0000_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0002_0000_0000_Description {
            get {
                return ResourceManager.GetString("Error_0002_0000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SG-1b ähnelt.
        /// </summary>
        internal static string Error_0002_0000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0002_0000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0002_0000_0000_Information {
            get {
                return ResourceManager.GetString("Error_0002_0000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schalten Sie ihr CASY für mindestens 5 Sekunden aus.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_0002_0000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0002_0000_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0004_0000_0000_Description {
            get {
                return ResourceManager.GetString("Error_0004_0000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0004_0000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0004_0000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0004_0000_0000_Information {
            get {
                return ResourceManager.GetString("Error_0004_0000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0004_0000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0004_0000_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0008_0000_0000_Description {
            get {
                return ResourceManager.GetString("Error_0008_0000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0008_0000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0008_0000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0008_0000_0000_Information {
            get {
                return ResourceManager.GetString("Error_0008_0000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0008_0000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0008_0000_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0010_0000_0000_Description {
            get {
                return ResourceManager.GetString("Error_0010_0000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0010_0000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0010_0000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0010_0000_0000_Information {
            get {
                return ResourceManager.GetString("Error_0010_0000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0010_0000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0010_0000_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0020_0000_0000_Description {
            get {
                return ResourceManager.GetString("Error_0020_0000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0020_0000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0020_0000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0020_0000_0000_Information {
            get {
                return ResourceManager.GetString("Error_0020_0000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0020_0000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0020_0000_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0040_0000_0000_Description {
            get {
                return ResourceManager.GetString("Error_0040_0000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0040_0000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0040_0000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0040_0000_0000_Information {
            get {
                return ResourceManager.GetString("Error_0040_0000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0040_0000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0040_0000_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0080_0000_0000_Description {
            get {
                return ResourceManager.GetString("Error_0080_0000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0080_0000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0080_0000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0080_0000_0000_Information {
            get {
                return ResourceManager.GetString("Error_0080_0000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0080_0000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0080_0000_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Drucker reagiert nicht. ähnelt.
        /// </summary>
        internal static string Error_0100_0000_0000_Description {
            get {
                return ResourceManager.GetString("Error_0100_0000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CM-1 ähnelt.
        /// </summary>
        internal static string Error_0100_0000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0100_0000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0100_0000_0000_Information {
            get {
                return ResourceManager.GetString("Error_0100_0000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überprüfen Sie, dass der Drucker verbunden und angeschaltet ist. ähnelt.
        /// </summary>
        internal static string Error_0100_0000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0100_0000_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Computer reagiert nicht ähnelt.
        /// </summary>
        internal static string Error_0200_0000_0000_Description {
            get {
                return ResourceManager.GetString("Error_0200_0000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CM-2 ähnelt.
        /// </summary>
        internal static string Error_0200_0000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0200_0000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0200_0000_0000_Information {
            get {
                return ResourceManager.GetString("Error_0200_0000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überprüfen Sie, dass der Computer verbunden und angeschaltet ist. ähnelt.
        /// </summary>
        internal static string Error_0200_0000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0200_0000_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0400_0000_0000_Description {
            get {
                return ResourceManager.GetString("Error_0400_0000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CL-1 ähnelt.
        /// </summary>
        internal static string Error_0400_0000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0400_0000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0400_0000_0000_Information {
            get {
                return ResourceManager.GetString("Error_0400_0000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schalten Sie ihr CASY für mindestens 5 Sekunden aus.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_0400_0000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0400_0000_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_0800_0000_0000_Description {
            get {
                return ResourceManager.GetString("Error_0800_0000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CL-2 ähnelt.
        /// </summary>
        internal static string Error_0800_0000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_0800_0000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESS ENTER TO CONFIRM OR PRINT TO GET A HARDCOPY ähnelt.
        /// </summary>
        internal static string Error_0800_0000_0000_Information {
            get {
                return ResourceManager.GetString("Error_0800_0000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schalten Sie ihr CASY für mindestens 5 Sekunden aus.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_0800_0000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_0800_0000_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_1000_0000_0000_Description {
            get {
                return ResourceManager.GetString("Error_1000_0000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CL-3 ähnelt.
        /// </summary>
        internal static string Error_1000_0000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_1000_0000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_1000_0000_0000_Information {
            get {
                return ResourceManager.GetString("Error_1000_0000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schalten Sie ihr CASY für mindestens 5 Sekunden aus.
        ///Wenn im Anschluss der Fehlercode weiterhin auftritt, kontaktieren Sie ihren lokalen Distributor. ähnelt.
        /// </summary>
        internal static string Error_1000_0000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_1000_0000_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_2000_0000_0000_Description {
            get {
                return ResourceManager.GetString("Error_2000_0000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_2000_0000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_2000_0000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_2000_0000_0000_Information {
            get {
                return ResourceManager.GetString("Error_2000_0000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_2000_0000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_2000_0000_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_4000_0000_0000_Description {
            get {
                return ResourceManager.GetString("Error_4000_0000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_4000_0000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_4000_0000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_4000_0000_0000_Information {
            get {
                return ResourceManager.GetString("Error_4000_0000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_4000_0000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_4000_0000_0000_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_8000_0000_0000_Description {
            get {
                return ResourceManager.GetString("Error_8000_0000_0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_8000_0000_0000_ErrorNumber {
            get {
                return ResourceManager.GetString("Error_8000_0000_0000_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_8000_0000_0000_Information {
            get {
                return ResourceManager.GetString("Error_8000_0000_0000_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Error_8000_0000_0000_Notice {
            get {
                return ResourceManager.GetString("Error_8000_0000_0000_Notice", resourceCulture);
            }
        }
    }
}
