//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLS.Casy.Ui.Base.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings_en_US() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLS.Casy.Ui.Base.Assets.Resources.ApplicationStrings_en-US", typeof(ApplicationStrings_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From Parents ähnelt.
        /// </summary>
        internal static string AggregationCalculationMode_FromParent_Name {
            get {
                return ResourceManager.GetString("AggregationCalculationMode_FromParent_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual ähnelt.
        /// </summary>
        internal static string AggregationCalculationMode_Manual_Name {
            get {
                return ResourceManager.GetString("AggregationCalculationMode_Manual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Off ähnelt.
        /// </summary>
        internal static string AggregationCalculationMode_Off_Name {
            get {
                return ResourceManager.GetString("AggregationCalculationMode_Off_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On ähnelt.
        /// </summary>
        internal static string AggregationCalculationMode_On_Name {
            get {
                return ResourceManager.GetString("AggregationCalculationMode_On_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result: ähnelt.
        /// </summary>
        internal static string BackgroundResultWizardStepView_Results_Header {
            get {
                return ResourceManager.GetString("BackgroundResultWizardStepView_Results_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counts /ml: ähnelt.
        /// </summary>
        internal static string BackgroundResultWizardStepView_Results_TotalCounts {
            get {
                return ResourceManager.GetString("BackgroundResultWizardStepView_Results_TotalCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dead cells ähnelt.
        /// </summary>
        internal static string Cursor_DeadCells_Name {
            get {
                return ResourceManager.GetString("Cursor_DeadCells_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debris ähnelt.
        /// </summary>
        internal static string Cursor_Debris_Name {
            get {
                return ResourceManager.GetString("Cursor_Debris_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Viable cells ähnelt.
        /// </summary>
        internal static string Cursor_VitalCells_Name {
            get {
                return ResourceManager.GetString("Cursor_VitalCells_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volume CASYton (ml) ähnelt.
        /// </summary>
        internal static string DilutionFactor_CASYtonVolume {
            get {
                return ResourceManager.GetString("DilutionFactor_CASYtonVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Factor ähnelt.
        /// </summary>
        internal static string DilutionFactor_Factor {
            get {
                return ResourceManager.GetString("DilutionFactor_Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sample Volume (µl) ähnelt.
        /// </summary>
        internal static string DilutionFactor_SampleVolume {
            get {
                return ResourceManager.GetString("DilutionFactor_SampleVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template with same name already exists. ähnelt.
        /// </summary>
        internal static string EditTemplateView_SetupAlreadyExists_Content {
            get {
                return ResourceManager.GetString("EditTemplateView_SetupAlreadyExists_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid name ähnelt.
        /// </summary>
        internal static string EditTemplateView_SetupAlreadyExists_Title {
            get {
                return ResourceManager.GetString("EditTemplateView_SetupAlreadyExists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert a value here ähnelt.
        /// </summary>
        internal static string InputDialog_Watermark {
            get {
                return ResourceManager.GetString("InputDialog_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free Ranges ähnelt.
        /// </summary>
        internal static string MeasureMode_MultipleCursor_Name {
            get {
                return ResourceManager.GetString("MeasureMode_MultipleCursor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Viability ähnelt.
        /// </summary>
        internal static string MeasureMode_Viability_Name {
            get {
                return ResourceManager.GetString("MeasureMode_Viability_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SELECTION: ähnelt.
        /// </summary>
        internal static string MeasureResultTreeView_Button_ChoosenElemtns {
            get {
                return ResourceManager.GetString("MeasureResultTreeView_Button_ChoosenElemtns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string ProgressDialog_Button_Cancel {
            get {
                return ResourceManager.GetString("ProgressDialog_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aggregation Factor ähnelt.
        /// </summary>
        internal static string ResultItemType_AggregationFactor_Name {
            get {
                return ResourceManager.GetString("ResultItemType_AggregationFactor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Concentration ähnelt.
        /// </summary>
        internal static string ResultItemType_Concentration_Name {
            get {
                return ResourceManager.GetString("ResultItemType_Concentration_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counts ähnelt.
        /// </summary>
        internal static string ResultItemType_Counts_Name {
            get {
                return ResourceManager.GetString("ResultItemType_Counts_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counts / ml &gt; {0} µm ähnelt.
        /// </summary>
        internal static string ResultItemType_CountsAboveDiameter_Name {
            get {
                return ResourceManager.GetString("ResultItemType_CountsAboveDiameter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % Counts ähnelt.
        /// </summary>
        internal static string ResultItemType_CountsPercentage_Name {
            get {
                return ResourceManager.GetString("ResultItemType_CountsPercentage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counts / ml ähnelt.
        /// </summary>
        internal static string ResultItemType_CountsPerMl_Name {
            get {
                return ResourceManager.GetString("ResultItemType_CountsPerMl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debri / ml ähnelt.
        /// </summary>
        internal static string ResultItemType_DebrisCount_Name {
            get {
                return ResourceManager.GetString("ResultItemType_DebrisCount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deviation ähnelt.
        /// </summary>
        internal static string ResultItemType_Deviation_Name {
            get {
                return ResourceManager.GetString("ResultItemType_Deviation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mean Diameter ähnelt.
        /// </summary>
        internal static string ResultItemType_MeanDiameter_Name {
            get {
                return ResourceManager.GetString("ResultItemType_MeanDiameter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mean Volume ähnelt.
        /// </summary>
        internal static string ResultItemType_MeanVolume_Name {
            get {
                return ResourceManager.GetString("ResultItemType_MeanVolume_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Peak Diameter ähnelt.
        /// </summary>
        internal static string ResultItemType_PeakDiameter_Name {
            get {
                return ResourceManager.GetString("ResultItemType_PeakDiameter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Peak Volume ähnelt.
        /// </summary>
        internal static string ResultItemType_PeakVolume_Name {
            get {
                return ResourceManager.GetString("ResultItemType_PeakVolume_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counts / ml (A) ähnelt.
        /// </summary>
        internal static string ResultItemType_SubpopulationACountsPerMl_Name {
            get {
                return ResourceManager.GetString("ResultItemType_SubpopulationACountsPerMl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % Counts (A) ähnelt.
        /// </summary>
        internal static string ResultItemType_SubpopulationAPercentage_Name {
            get {
                return ResourceManager.GetString("ResultItemType_SubpopulationAPercentage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counts / ml (B) ähnelt.
        /// </summary>
        internal static string ResultItemType_SubpopulationBCountsPerMl_Name {
            get {
                return ResourceManager.GetString("ResultItemType_SubpopulationBCountsPerMl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % Counts (B) ähnelt.
        /// </summary>
        internal static string ResultItemType_SubpopulationBPercentage_Name {
            get {
                return ResourceManager.GetString("ResultItemType_SubpopulationBPercentage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counts / ml (C) ähnelt.
        /// </summary>
        internal static string ResultItemType_SubpopulationCCountsPerMl_Name {
            get {
                return ResourceManager.GetString("ResultItemType_SubpopulationCCountsPerMl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % Counts (C) ähnelt.
        /// </summary>
        internal static string ResultItemType_SubpopulationCPercentage_Name {
            get {
                return ResourceManager.GetString("ResultItemType_SubpopulationCPercentage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counts / ml (D) ähnelt.
        /// </summary>
        internal static string ResultItemType_SubpopulationDCountsPerMl_Name {
            get {
                return ResourceManager.GetString("ResultItemType_SubpopulationDCountsPerMl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % Counts (D) ähnelt.
        /// </summary>
        internal static string ResultItemType_SubpopulationDPercentage_Name {
            get {
                return ResourceManager.GetString("ResultItemType_SubpopulationDPercentage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counts / ml (E) ähnelt.
        /// </summary>
        internal static string ResultItemType_SubpopulationECountsPerMl_Name {
            get {
                return ResourceManager.GetString("ResultItemType_SubpopulationECountsPerMl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % Counts (E) ähnelt.
        /// </summary>
        internal static string ResultItemType_SubpopulationEPercentage_Name {
            get {
                return ResourceManager.GetString("ResultItemType_SubpopulationEPercentage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total Cells / ml ähnelt.
        /// </summary>
        internal static string ResultItemType_TotalCountsPerMl_Name {
            get {
                return ResourceManager.GetString("ResultItemType_TotalCountsPerMl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die %Viability ähnelt.
        /// </summary>
        internal static string ResultItemType_Viability_Name {
            get {
                return ResourceManager.GetString("ResultItemType_Viability_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Viable Cells / ml ähnelt.
        /// </summary>
        internal static string ResultItemType_ViableCellsPerMl_Name {
            get {
                return ResourceManager.GetString("ResultItemType_ViableCellsPerMl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volume / ml ähnelt.
        /// </summary>
        internal static string ResultItemType_VolumePerMl_Name {
            get {
                return ResourceManager.GetString("ResultItemType_VolumePerMl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto Range ähnelt.
        /// </summary>
        internal static string ScalingMode_Auto_Name {
            get {
                return ResourceManager.GetString("ScalingMode_Auto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max Range ähnelt.
        /// </summary>
        internal static string ScalingMode_MaxRange_Name {
            get {
                return ResourceManager.GetString("ScalingMode_MaxRange_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SELECT CAPILLARY ähnelt.
        /// </summary>
        internal static string SelectCapillaryWizardStepView_ComboBox_Capillary_Watermark {
            get {
                return ResourceManager.GetString("SelectCapillaryWizardStepView_ComboBox_Capillary_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Different range settings detected ähnelt.
        /// </summary>
        internal static string SelectRangeParentDialog_Header {
            get {
                return ResourceManager.GetString("SelectRangeParentDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please choose measurement you want to apply range settings to overlay view ähnelt.
        /// </summary>
        internal static string SelectRangeParentDialog_Text {
            get {
                return ResourceManager.GetString("SelectRangeParentDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time left: ähnelt.
        /// </summary>
        internal static string TimerWizzardStepView_TimeLeft {
            get {
                return ResourceManager.GetString("TimerWizzardStepView_TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counts ähnelt.
        /// </summary>
        internal static string UnitMode_Counts_Name {
            get {
                return ResourceManager.GetString("UnitMode_Counts_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volume ähnelt.
        /// </summary>
        internal static string UnitMode_Volume_Name {
            get {
                return ResourceManager.GetString("UnitMode_Volume_Name", resourceCulture);
            }
        }
    }
}
