//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLS.Casy.Controller.Measure.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings_de_DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLS.Casy.Controller.Measure.Assets.Resources.ApplicationStrings_de-DE", typeof(ApplicationStrings_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Während des Spülens sind Fehler aufgetreten.
        ///Bitte benutze den &quot;Kapillare Reinigen Wizard&quot; im Servicemenü. ähnelt.
        /// </summary>
        internal static string MeasureController_CleanResult_Content_Failed {
            get {
                return ResourceManager.GetString("MeasureController_CleanResult_Content_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tausche das CASYcup mit CASYton mit dem CASYcup mit Probe und fahre mit der Messung fort.
        ///Sollten weiterhin Probleme auftreten, benutze den &quot;Kapillare Reinigen Wizard&quot; im Servicemenü.
        /// ähnelt.
        /// </summary>
        internal static string MeasureController_CleanResult_Content_Success {
            get {
                return ResourceManager.GetString("MeasureController_CleanResult_Content_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reinigung abgeschlossen ähnelt.
        /// </summary>
        internal static string MeasureController_CleanResult_Title {
            get {
                return ResourceManager.GetString("MeasureController_CleanResult_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} {1} ähnelt.
        /// </summary>
        internal static string MeasureController_TemporaryMeasureResultName {
            get {
                return ResourceManager.GetString("MeasureController_TemporaryMeasureResultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein Messprotokoll ausgewählt ähnelt.
        /// </summary>
        internal static string MeasureController_TemporaryTemplateName {
            get {
                return ResourceManager.GetString("MeasureController_TemporaryTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fortfahren ähnelt.
        /// </summary>
        internal static string MessageBox_Button_Continue_Text {
            get {
                return ResourceManager.GetString("MessageBox_Button_Continue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reinige 3x ähnelt.
        /// </summary>
        internal static string MessageBox_Button_Retry_3x_Text {
            get {
                return ResourceManager.GetString("MessageBox_Button_Retry_3x_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erhöhte Abweichung detektiert für &apos;{0}&apos;. Erlaubter Maximalwert: {1}. Berechneter Wert: {2}. ähnelt.
        /// </summary>
        internal static string MessageBox_DeviationControl_MaxViolation_Message {
            get {
                return ResourceManager.GetString("MessageBox_DeviationControl_MaxViolation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erhöhte Abweichung detektiert für &apos;{0}&apos;. Erlaubter Minimalwert: {1}. Berechneter Wert: {2}. ähnelt.
        /// </summary>
        internal static string MessageBox_DeviationControl_MinViolation_Message {
            get {
                return ResourceManager.GetString("MessageBox_DeviationControl_MinViolation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erhöhte Abweichung detektiert ähnelt.
        /// </summary>
        internal static string MessageBox_DeviationControl_Title {
            get {
                return ResourceManager.GetString("MessageBox_DeviationControl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ähnelt.
        /// </summary>
        internal static string ProgressBox_Measure_Message {
            get {
                return ResourceManager.GetString("ProgressBox_Measure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Berechne Messergebnisse ... ähnelt.
        /// </summary>
        internal static string ProgressBox_Measure_Message_CalculateResultData {
            get {
                return ResourceManager.GetString("ProgressBox_Measure_Message_CalculateResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kalibriere ... ähnelt.
        /// </summary>
        internal static string ProgressBox_Measure_Message_Calibration {
            get {
                return ResourceManager.GetString("ProgressBox_Measure_Message_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messdurchgang {0} von {1} wird ausgeführt ... ähnelt.
        /// </summary>
        internal static string ProgressBox_Measure_Message_StartingRepeat {
            get {
                return ResourceManager.GetString("ProgressBox_Measure_Message_StartingRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messung wird durchgeführt ... ähnelt.
        /// </summary>
        internal static string ProgressBox_Measure_Title {
            get {
                return ResourceManager.GetString("ProgressBox_Measure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spüle {0} mal. ähnelt.
        /// </summary>
        internal static string ProgressBox_Purge_Message {
            get {
                return ResourceManager.GetString("ProgressBox_Purge_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messkopf wird gespült ähnelt.
        /// </summary>
        internal static string ProgressBox_Purge_Title {
            get {
                return ResourceManager.GetString("ProgressBox_Purge_Title", resourceCulture);
            }
        }
    }
}
