//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLS.Casy.Controller.Measure.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings_en_US() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLS.Casy.Controller.Measure.Assets.Resources.ApplicationStrings_en-US", typeof(ApplicationStrings_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured while purging the system.
        ///Please refer to “Clean Capillary Wizard” in Service Menu. ähnelt.
        /// </summary>
        internal static string MeasureController_CleanResult_Content_Failed {
            get {
                return ResourceManager.GetString("MeasureController_CleanResult_Content_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exchange CASYcup to the one including the sample and continue the measurement
        ///In case the problem persists refer to “Clean Capillary Wizard” in Service Menu. ähnelt.
        /// </summary>
        internal static string MeasureController_CleanResult_Content_Success {
            get {
                return ResourceManager.GetString("MeasureController_CleanResult_Content_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finished purging ähnelt.
        /// </summary>
        internal static string MeasureController_CleanResult_Title {
            get {
                return ResourceManager.GetString("MeasureController_CleanResult_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} {1} ähnelt.
        /// </summary>
        internal static string MeasureController_TemporaryMeasureResultName {
            get {
                return ResourceManager.GetString("MeasureController_TemporaryMeasureResultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No template selected ähnelt.
        /// </summary>
        internal static string MeasureController_TemporaryTemplateName {
            get {
                return ResourceManager.GetString("MeasureController_TemporaryTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue ähnelt.
        /// </summary>
        internal static string MessageBox_Button_Continue_Text {
            get {
                return ResourceManager.GetString("MessageBox_Button_Continue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Purge 3x ähnelt.
        /// </summary>
        internal static string MessageBox_Button_Retry_3x_Text {
            get {
                return ResourceManager.GetString("MessageBox_Button_Retry_3x_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deviation violation detected for &apos;{0}&apos;. Allowed max value: {1}. Calculated value: {2}. ähnelt.
        /// </summary>
        internal static string MessageBox_DeviationControl_MaxViolation_Message {
            get {
                return ResourceManager.GetString("MessageBox_DeviationControl_MaxViolation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deviation violation detected for &apos;{0}&apos;. Allowed min value: {1}. Calculated value: {2}. ähnelt.
        /// </summary>
        internal static string MessageBox_DeviationControl_MinViolation_Message {
            get {
                return ResourceManager.GetString("MessageBox_DeviationControl_MinViolation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deviation violation detected ähnelt.
        /// </summary>
        internal static string MessageBox_DeviationControl_Title {
            get {
                return ResourceManager.GetString("MessageBox_DeviationControl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ähnelt.
        /// </summary>
        internal static string ProgressBox_Measure_Message {
            get {
                return ResourceManager.GetString("ProgressBox_Measure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculating results ... ähnelt.
        /// </summary>
        internal static string ProgressBox_Measure_Message_CalculateResultData {
            get {
                return ResourceManager.GetString("ProgressBox_Measure_Message_CalculateResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calibrating ... ähnelt.
        /// </summary>
        internal static string ProgressBox_Measure_Message_Calibration {
            get {
                return ResourceManager.GetString("ProgressBox_Measure_Message_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measurement repeat {0} of {1} in progress ... ähnelt.
        /// </summary>
        internal static string ProgressBox_Measure_Message_StartingRepeat {
            get {
                return ResourceManager.GetString("ProgressBox_Measure_Message_StartingRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measurement in progress ähnelt.
        /// </summary>
        internal static string ProgressBox_Measure_Title {
            get {
                return ResourceManager.GetString("ProgressBox_Measure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Purging {0} times ... ähnelt.
        /// </summary>
        internal static string ProgressBox_Purge_Message {
            get {
                return ResourceManager.GetString("ProgressBox_Purge_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Purge in progress ähnelt.
        /// </summary>
        internal static string ProgressBox_Purge_Title {
            get {
                return ResourceManager.GetString("ProgressBox_Purge_Title", resourceCulture);
            }
        }
    }
}
