//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLS.Casy.Controller.Service.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings_en_US() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLS.Casy.Controller.Service.Assets.Resources.ApplicationStrings_en-US", typeof(ApplicationStrings_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Background measurement ähnelt.
        /// </summary>
        internal static string BackgroundWizard_Title {
            get {
                return ResourceManager.GetString("BackgroundWizard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please note ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Initial_PrimaryHeader {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Initial_PrimaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This wizard will control the current background level of the instrument ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Initial_PrimaryText {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Initial_PrimaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Items needed ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Initial_SecondaryHeader {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Initial_SecondaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CASYton ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Initial_SecondaryText {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Initial_SecondaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accept ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Result_Button_Accept {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Result_Button_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repeat ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Result_Button_Repeat {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Result_Button_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result: ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Result_Header {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Result_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Background measurement completed ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Result_Text {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Result_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured while measuring background. Please follow the instructions and repeat the operation. ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Result_Text_Error {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Result_Text_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select installed capillary ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_SelectCapillary_Header {
            get {
                return ResourceManager.GetString("BackgroundWizzard_SelectCapillary_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The wizard can be performed for several capillary sizes.
        ///Please select the capillary that is installed with the instrument ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_SelectCapillary_Text {
            get {
                return ResourceManager.GetString("BackgroundWizzard_SelectCapillary_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Instructions ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Step1_PrimaryHeader {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Step1_PrimaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Put one CASYcup filled with 10ml &lt;Bold&gt;&lt;Underline&gt;CASYton&lt;/Underline&gt;&lt;/Bold&gt; under capillary ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Step1_PrimaryText {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Step1_PrimaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next steps ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Step1_SecondaryHeader {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Step1_SecondaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CASY will perform &lt;Bold&gt;&lt;Underline&gt;one&lt;/Underline&gt;&lt;/Bold&gt; background measurement with &lt;Bold&gt;&lt;Underline&gt;CASYton&lt;/Underline&gt;&lt;/Bold&gt; and evaluate the results ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Step1_SecondaryText {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Step1_SecondaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Service ähnelt.
        /// </summary>
        internal static string Notification_WeeklyClean_Action {
            get {
                return ResourceManager.GetString("Notification_WeeklyClean_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It&apos;s more than a week ago you did a weekly clean. Please consider doing it now. ähnelt.
        /// </summary>
        internal static string Notification_WeeklyClean_Message {
            get {
                return ResourceManager.GetString("Notification_WeeklyClean_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weekly clean recommanded ähnelt.
        /// </summary>
        internal static string Notification_WeeklyClean_Title {
            get {
                return ResourceManager.GetString("Notification_WeeklyClean_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A mandatory weekly clean routine must be performed within {0} hours. ATTENTION: It&apos;s not possible to measure after time has expired. ähnelt.
        /// </summary>
        internal static string Notification_WeeklyCleanAnnouncement_Message {
            get {
                return ResourceManager.GetString("Notification_WeeklyCleanAnnouncement_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weekly Clean Announcement ähnelt.
        /// </summary>
        internal static string Notification_WeeklyCleanAnnouncement_Title {
            get {
                return ResourceManager.GetString("Notification_WeeklyCleanAnnouncement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It&apos;s more than a week ago you did a weekly clean. It&apos;s mandatory to execute the weekly clean routine now. ähnelt.
        /// </summary>
        internal static string Notification_WeeklyCleanMandatory_Message {
            get {
                return ResourceManager.GetString("Notification_WeeklyCleanMandatory_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weekly clean mandatory ähnelt.
        /// </summary>
        internal static string Notification_WeeklyCleanMandatory_Title {
            get {
                return ResourceManager.GetString("Notification_WeeklyCleanMandatory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Service ähnelt.
        /// </summary>
        internal static string Notification_WeeklyCleanRecommanded_ButtonText {
            get {
                return ResourceManager.GetString("Notification_WeeklyCleanRecommanded_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It&apos;s more than a week ago you did a weekly clean. Consider execute the weekly clean wizard now. ähnelt.
        /// </summary>
        internal static string Notification_WeeklyCleanRecommanded_Message {
            get {
                return ResourceManager.GetString("Notification_WeeklyCleanRecommanded_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weekly Clean Recommended ähnelt.
        /// </summary>
        internal static string Notification_WeeklyCleanRecommanded_Title {
            get {
                return ResourceManager.GetString("Notification_WeeklyCleanRecommanded_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ähnelt.
        /// </summary>
        internal static string ProgressBox_Background_Message {
            get {
                return ResourceManager.GetString("ProgressBox_Background_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculating Results ... ähnelt.
        /// </summary>
        internal static string ProgressBox_Background_Message_Calculate {
            get {
                return ResourceManager.GetString("ProgressBox_Background_Message_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calibrating ... ähnelt.
        /// </summary>
        internal static string ProgressBox_Background_Message_Calibration {
            get {
                return ResourceManager.GetString("ProgressBox_Background_Message_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measuring … ähnelt.
        /// </summary>
        internal static string ProgressBox_Background_Message_Measure {
            get {
                return ResourceManager.GetString("ProgressBox_Background_Message_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Retrieving Result ... ähnelt.
        /// </summary>
        internal static string ProgressBox_Background_Message_Results {
            get {
                return ResourceManager.GetString("ProgressBox_Background_Message_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Performing Background Measurement ähnelt.
        /// </summary>
        internal static string ProgressBox_Background_Title {
            get {
                return ResourceManager.GetString("ProgressBox_Background_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Performing Rise Time Check … ähnelt.
        /// </summary>
        internal static string ProgressBox_CheckRisetime_Message {
            get {
                return ResourceManager.GetString("ProgressBox_CheckRisetime_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checking Rise Time ... ähnelt.
        /// </summary>
        internal static string ProgressBox_CheckRisetime_Title {
            get {
                return ResourceManager.GetString("ProgressBox_CheckRisetime_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Performing Tightness Test … ähnelt.
        /// </summary>
        internal static string ProgressBox_CheckTightness_Message {
            get {
                return ResourceManager.GetString("ProgressBox_CheckTightness_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checking Tightness ähnelt.
        /// </summary>
        internal static string ProgressBox_CheckTightness_Title {
            get {
                return ResourceManager.GetString("ProgressBox_CheckTightness_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drying the system ... ähnelt.
        /// </summary>
        internal static string ProgressBox_Dry_Message {
            get {
                return ResourceManager.GetString("ProgressBox_Dry_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drying ähnelt.
        /// </summary>
        internal static string ProgressBox_Dry_Title {
            get {
                return ResourceManager.GetString("ProgressBox_Dry_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ähnelt.
        /// </summary>
        internal static string ProgressBox_TestPattern_Message {
            get {
                return ResourceManager.GetString("ProgressBox_TestPattern_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calibrating ... ähnelt.
        /// </summary>
        internal static string ProgressBox_TestPattern_Message_Calibration {
            get {
                return ResourceManager.GetString("ProgressBox_TestPattern_Message_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creating Test Pattern ... ähnelt.
        /// </summary>
        internal static string ProgressBox_TestPattern_Message_CreateTestPattern {
            get {
                return ResourceManager.GetString("ProgressBox_TestPattern_Message_CreateTestPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Retrieving Test Pattern ... ähnelt.
        /// </summary>
        internal static string ProgressBox_TestPattern_Message_RetrieveTestPattern {
            get {
                return ResourceManager.GetString("ProgressBox_TestPattern_Message_RetrieveTestPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Requesting Test Pattern ähnelt.
        /// </summary>
        internal static string ProgressBox_TestPattern_Title {
            get {
                return ResourceManager.GetString("ProgressBox_TestPattern_Title", resourceCulture);
            }
        }
    }
}
