//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLS.Casy.Controller.Service.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings_de_DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLS.Casy.Controller.Service.Assets.Resources.ApplicationStrings_de-DE", typeof(ApplicationStrings_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leerwertmessung ähnelt.
        /// </summary>
        internal static string BackgroundWizard_Title {
            get {
                return ResourceManager.GetString("BackgroundWizard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte beachte: ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Initial_PrimaryHeader {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Initial_PrimaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diese Routine kontrolliert den aktuellen Leerwert-Level des Geräts ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Initial_PrimaryText {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Initial_PrimaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benötigte Materialien ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Initial_SecondaryHeader {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Initial_SecondaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CASYton ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Initial_SecondaryText {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Initial_SecondaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Akzeptieren ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Result_Button_Accept {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Result_Button_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wiederholen ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Result_Button_Repeat {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Result_Button_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ergebnis: ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Result_Header {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Result_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Leerwertmessung wurde mit dem folgenden Ergebnis durchgeführt. ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Result_Text {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Result_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein Fehler während der Leerwertmessung aufgetreten. Bitte befolge die Instruktionen und wiederhole den Vorgang. ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Result_Text_Error {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Result_Text_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installierte Kapillare auswählen ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_SelectCapillary_Header {
            get {
                return ResourceManager.GetString("BackgroundWizzard_SelectCapillary_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Wizard kann für verschiedene installierte Kapillaren durchgeführt werden.
        ///Es ist notwendig, dass du die z.Z. installierte Kapillargröße auswählst. ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_SelectCapillary_Text {
            get {
                return ResourceManager.GetString("BackgroundWizzard_SelectCapillary_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anweisungen ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Step1_PrimaryHeader {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Step1_PrimaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stelle ein CASYcup gefüllt mit 10 ml &lt;Bold&gt;&lt;Underline&gt;CASYton&lt;/Underline&gt;&lt;/Bold&gt; unter die Kapillare. ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Step1_PrimaryText {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Step1_PrimaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nächste Schritte ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Step1_SecondaryHeader {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Step1_SecondaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CASY wird nun &lt;Bold&gt;&lt;Underline&gt;eine&lt;/Underline&gt;&lt;/Bold&gt; Leerwertmessung mit &lt;Bold&gt;&lt;Underline&gt;CASYton&lt;/Underline&gt;&lt;/Bold&gt; durchführen und das Ergebnis auswerten ähnelt.
        /// </summary>
        internal static string BackgroundWizzard_Step1_SecondaryText {
            get {
                return ResourceManager.GetString("BackgroundWizzard_Step1_SecondaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service anzeigen ähnelt.
        /// </summary>
        internal static string Notification_WeeklyClean_Action {
            get {
                return ResourceManager.GetString("Notification_WeeklyClean_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die letzte wöchentliche Reinigung ist länger als eine Woche her. Es wird empfohlen, diese jetzt durchzuführen. ähnelt.
        /// </summary>
        internal static string Notification_WeeklyClean_Message {
            get {
                return ResourceManager.GetString("Notification_WeeklyClean_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wöchentliche Reinigung empfohlen ähnelt.
        /// </summary>
        internal static string Notification_WeeklyClean_Title {
            get {
                return ResourceManager.GetString("Notification_WeeklyClean_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine wöchentliche Reinigungsroutine ist in den nächsten {0} fällig. ACHTUNG: Nach Ablauf der Zeit sind keine Messungen mehr möglich ähnelt.
        /// </summary>
        internal static string Notification_WeeklyCleanAnnouncement_Message {
            get {
                return ResourceManager.GetString("Notification_WeeklyCleanAnnouncement_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ankündigung Wöchtentliche Reinigung ähnelt.
        /// </summary>
        internal static string Notification_WeeklyCleanAnnouncement_Title {
            get {
                return ResourceManager.GetString("Notification_WeeklyCleanAnnouncement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die letzte wöchentliche Reinigung ist länger als eine Woche her. Es ist zwingend erforderlich, diese jetzt durchzuführen. ähnelt.
        /// </summary>
        internal static string Notification_WeeklyCleanMandatory_Message {
            get {
                return ResourceManager.GetString("Notification_WeeklyCleanMandatory_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wöchentliche Reinigung erforderlich ähnelt.
        /// </summary>
        internal static string Notification_WeeklyCleanMandatory_Title {
            get {
                return ResourceManager.GetString("Notification_WeeklyCleanMandatory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service anzeigen ähnelt.
        /// </summary>
        internal static string Notification_WeeklyCleanRecommanded_ButtonText {
            get {
                return ResourceManager.GetString("Notification_WeeklyCleanRecommanded_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist länger als eine Woche her, dass du die wöchentliche Reinigungsroutine genutzt hast. Möchtest du dies nun erledigen? ähnelt.
        /// </summary>
        internal static string Notification_WeeklyCleanRecommanded_Message {
            get {
                return ResourceManager.GetString("Notification_WeeklyCleanRecommanded_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wöchentliche Reinigungsroutine empfohlen ähnelt.
        /// </summary>
        internal static string Notification_WeeklyCleanRecommanded_Title {
            get {
                return ResourceManager.GetString("Notification_WeeklyCleanRecommanded_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ähnelt.
        /// </summary>
        internal static string ProgressBox_Background_Message {
            get {
                return ResourceManager.GetString("ProgressBox_Background_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Berechne Messergebnisse ... ähnelt.
        /// </summary>
        internal static string ProgressBox_Background_Message_Calculate {
            get {
                return ResourceManager.GetString("ProgressBox_Background_Message_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kalibrierung ... ähnelt.
        /// </summary>
        internal static string ProgressBox_Background_Message_Calibration {
            get {
                return ResourceManager.GetString("ProgressBox_Background_Message_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messung ... ähnelt.
        /// </summary>
        internal static string ProgressBox_Background_Message_Measure {
            get {
                return ResourceManager.GetString("ProgressBox_Background_Message_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empfange Ergebnis ... ähnelt.
        /// </summary>
        internal static string ProgressBox_Background_Message_Results {
            get {
                return ResourceManager.GetString("ProgressBox_Background_Message_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leerwertmessung durchführen ähnelt.
        /// </summary>
        internal static string ProgressBox_Background_Title {
            get {
                return ResourceManager.GetString("ProgressBox_Background_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überprüfung der Steigzeiten läuft … ähnelt.
        /// </summary>
        internal static string ProgressBox_CheckRisetime_Message {
            get {
                return ResourceManager.GetString("ProgressBox_CheckRisetime_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überprüfung Steigzeiten ähnelt.
        /// </summary>
        internal static string ProgressBox_CheckRisetime_Title {
            get {
                return ResourceManager.GetString("ProgressBox_CheckRisetime_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überprüfung der Dichtigkeit läuft … ähnelt.
        /// </summary>
        internal static string ProgressBox_CheckTightness_Message {
            get {
                return ResourceManager.GetString("ProgressBox_CheckTightness_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überprüfung der Dichtigkeit ähnelt.
        /// </summary>
        internal static string ProgressBox_CheckTightness_Title {
            get {
                return ResourceManager.GetString("ProgressBox_CheckTightness_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trockne das System ... ähnelt.
        /// </summary>
        internal static string ProgressBox_Dry_Message {
            get {
                return ResourceManager.GetString("ProgressBox_Dry_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trocknen ähnelt.
        /// </summary>
        internal static string ProgressBox_Dry_Title {
            get {
                return ResourceManager.GetString("ProgressBox_Dry_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ähnelt.
        /// </summary>
        internal static string ProgressBox_TestPattern_Message {
            get {
                return ResourceManager.GetString("ProgressBox_TestPattern_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kalibrierung ... ähnelt.
        /// </summary>
        internal static string ProgressBox_TestPattern_Message_Calibration {
            get {
                return ResourceManager.GetString("ProgressBox_TestPattern_Message_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erzeuge Testmuster ... ähnelt.
        /// </summary>
        internal static string ProgressBox_TestPattern_Message_CreateTestPattern {
            get {
                return ResourceManager.GetString("ProgressBox_TestPattern_Message_CreateTestPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empfange Testmuster ... ähnelt.
        /// </summary>
        internal static string ProgressBox_TestPattern_Message_RetrieveTestPattern {
            get {
                return ResourceManager.GetString("ProgressBox_TestPattern_Message_RetrieveTestPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fordere Testmuster an ähnelt.
        /// </summary>
        internal static string ProgressBox_TestPattern_Title {
            get {
                return ResourceManager.GetString("ProgressBox_TestPattern_Title", resourceCulture);
            }
        }
    }
}
