//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLS.Casy.Ui.Core.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings_en_US() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLS.Casy.Ui.Core.Assets.Resources.ApplicationStrings_en-US", typeof(ApplicationStrings_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add a comment ähnelt.
        /// </summary>
        internal static string AddCommentDialog_Title {
            get {
                return ResourceManager.GetString("AddCommentDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to replace measurement result &apos;{0}&apos;? ähnelt.
        /// </summary>
        internal static string ConfirmOverrideDialog_Message {
            get {
                return ResourceManager.GetString("ConfirmOverrideDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overwrite measurement result? ähnelt.
        /// </summary>
        internal static string ConfirmOverrideDialog_Title {
            get {
                return ResourceManager.GetString("ConfirmOverrideDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The measurement results &apos;{0}&apos; have unsaved changes. How would you like to proceed? ähnelt.
        /// </summary>
        internal static string ConfirmSaveMeasureResultsOnCloseDialog_Content {
            get {
                return ResourceManager.GetString("ConfirmSaveMeasureResultsOnCloseDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsaved changes ähnelt.
        /// </summary>
        internal static string ConfirmSaveMeasureResultsOnCloseDialog_Title {
            get {
                return ResourceManager.GetString("ConfirmSaveMeasureResultsOnCloseDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the selected range? ähnelt.
        /// </summary>
        internal static string DeleteCursorDialog_Content {
            get {
                return ResourceManager.GetString("DeleteCursorDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete range ähnelt.
        /// </summary>
        internal static string DeleteCursorDialog_Title {
            get {
                return ResourceManager.GetString("DeleteCursorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete measurement result &apos;{0}&apos;? ähnelt.
        /// </summary>
        internal static string DeleteMesureResult_ConfirmDialog_Content {
            get {
                return ResourceManager.GetString("DeleteMesureResult_ConfirmDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete measurement result ähnelt.
        /// </summary>
        internal static string DeleteMesureResult_ConfirmDialog_Title {
            get {
                return ResourceManager.GetString("DeleteMesureResult_ConfirmDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are about to delete template &apos;{0}&apos;. Please confirm if you want to continue. ähnelt.
        /// </summary>
        internal static string DeleteTemplateDialog_Content {
            get {
                return ResourceManager.GetString("DeleteTemplateDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete template ähnelt.
        /// </summary>
        internal static string DeleteTemplateDialog_Title {
            get {
                return ResourceManager.GetString("DeleteTemplateDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PAGE: ähnelt.
        /// </summary>
        internal static string DocumentBase_Footer_Page {
            get {
                return ResourceManager.GetString("DocumentBase_Footer_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die of ähnelt.
        /// </summary>
        internal static string DocumentBase_Footer_Page_Of {
            get {
                return ResourceManager.GetString("DocumentBase_Footer_Page_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DATE OF PRINT: ähnelt.
        /// </summary>
        internal static string DocumentBase_Footer_PrintDate {
            get {
                return ResourceManager.GetString("DocumentBase_Footer_PrintDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die USER: ähnelt.
        /// </summary>
        internal static string DocumentBase_Footer_User {
            get {
                return ResourceManager.GetString("DocumentBase_Footer_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show date of last successfully performed weekly clean routine ähnelt.
        /// </summary>
        internal static string DocumentSettingsView_CfrSection_ShowLastWeeklyClean {
            get {
                return ResourceManager.GetString("DocumentSettingsView_CfrSection_ShowLastWeeklyClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CFR RELATED SETTINGS ähnelt.
        /// </summary>
        internal static string DocumentSettingsView_CfrSection_Title {
            get {
                return ResourceManager.GetString("DocumentSettingsView_CfrSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected Logo ähnelt.
        /// </summary>
        internal static string DocumentSettingsView_DocumentLogo_Watermark {
            get {
                return ResourceManager.GetString("DocumentSettingsView_DocumentLogo_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DOCUMENT LOGO ähnelt.
        /// </summary>
        internal static string DocumentSettingsView_LogoSection_Title {
            get {
                return ResourceManager.GetString("DocumentSettingsView_LogoSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audit Trail ähnelt.
        /// </summary>
        internal static string EditTemplateDialog_Button_AuditTrail {
            get {
                return ResourceManager.GetString("EditTemplateDialog_Button_AuditTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EXPORT ähnelt.
        /// </summary>
        internal static string EditTemplateDialog_Button_Export {
            get {
                return ResourceManager.GetString("EditTemplateDialog_Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IMPORT
        /// ähnelt.
        /// </summary>
        internal static string EditTemplateDialog_Button_Import {
            get {
                return ResourceManager.GetString("EditTemplateDialog_Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SAVE ähnelt.
        /// </summary>
        internal static string EditTemplateDialog_Button_Save {
            get {
                return ResourceManager.GetString("EditTemplateDialog_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save as copy ähnelt.
        /// </summary>
        internal static string EditTemplateDialog_Button_SaveAs {
            get {
                return ResourceManager.GetString("EditTemplateDialog_Button_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Templates: ähnelt.
        /// </summary>
        internal static string EditTemplateDialog_Header {
            get {
                return ResourceManager.GetString("EditTemplateDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAPILLARY ähnelt.
        /// </summary>
        internal static string EditTemplateView_ComboBox_Capillary_Watermark {
            get {
                return ResourceManager.GetString("EditTemplateView_ComboBox_Capillary_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Experiment ähnelt.
        /// </summary>
        internal static string EditTemplateView_ComboBox_Experiment_Watermark {
            get {
                return ResourceManager.GetString("EditTemplateView_ComboBox_Experiment_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group ähnelt.
        /// </summary>
        internal static string EditTemplateView_ComboBox_Group_Watermark {
            get {
                return ResourceManager.GetString("EditTemplateView_ComboBox_Group_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X-RANGE ähnelt.
        /// </summary>
        internal static string EditTemplateView_ComboBox_ToDiameter_Watermark {
            get {
                return ResourceManager.GetString("EditTemplateView_ComboBox_ToDiameter_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AGGREGATION: ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_Aggregation {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_Aggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die COMMENT REQUIRED ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_AutoComment {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_AutoComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enforce Auto Save: ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_AutoSave {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CYCLES ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_Counts {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_Counts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DEVIATION CONTROL CYCLES: ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_DeviationControl {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_DeviationControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DILUTION ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_Dilution {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_Dilution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MODE ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_MeasureMode {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_MeasureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SMOOTHING: ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_Smoothing {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_Smoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VOLUME ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_Volume {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y-SCALE: ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_YScale {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_YScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DEFAULT NAME ähnelt.
        /// </summary>
        internal static string EditTemplateView_OmniTextBox_AutoSaveName_Watermark {
            get {
                return ResourceManager.GetString("EditTemplateView_OmniTextBox_AutoSaveName_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual Value ähnelt.
        /// </summary>
        internal static string EditTemplateView_OmniTextBox_ManualAggregationCalculationFactor_Watermark {
            get {
                return ResourceManager.GetString("EditTemplateView_OmniTextBox_ManualAggregationCalculationFactor_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template name ähnelt.
        /// </summary>
        internal static string EditTemplateView_OmniTextBox_Name_Watermark {
            get {
                return ResourceManager.GetString("EditTemplateView_OmniTextBox_Name_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MAX. RANGE ähnelt.
        /// </summary>
        internal static string EditTemplateView_OmniTextBox_ScalingMaxRange_Watermark {
            get {
                return ResourceManager.GetString("EditTemplateView_OmniTextBox_ScalingMaxRange_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto ähnelt.
        /// </summary>
        internal static string EditTemplateView_Value_AutoRange {
            get {
                return ResourceManager.GetString("EditTemplateView_Value_AutoRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counts ähnelt.
        /// </summary>
        internal static string EditTemplateView_Value_Counts {
            get {
                return ResourceManager.GetString("EditTemplateView_Value_Counts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volume ähnelt.
        /// </summary>
        internal static string EditTemplateView_Value_Volume {
            get {
                return ResourceManager.GetString("EditTemplateView_Value_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attention! Changing this template setting will reset the defined ranges. ähnelt.
        /// </summary>
        internal static string EditTemplateViewModel_ResetCursorMessage_Message {
            get {
                return ResourceManager.GetString("EditTemplateViewModel_ResetCursorMessage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ranges will be reseted ähnelt.
        /// </summary>
        internal static string EditTemplateViewModel_ResetCursorMessage_Title {
            get {
                return ResourceManager.GetString("EditTemplateViewModel_ResetCursorMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export ähnelt.
        /// </summary>
        internal static string ExportDialog_Button_Export {
            get {
                return ResourceManager.GetString("ExportDialog_Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        internal static string ExportDialog_Button_Next {
            get {
                return ResourceManager.GetString("ExportDialog_Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Experiment ähnelt.
        /// </summary>
        internal static string ExportDialog_ComboBox_Experiment_Watermark {
            get {
                return ResourceManager.GetString("ExportDialog_ComboBox_Experiment_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group ähnelt.
        /// </summary>
        internal static string ExportDialog_ComboBox_Group_Watermark {
            get {
                return ResourceManager.GetString("ExportDialog_ComboBox_Group_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date of Measurement: ähnelt.
        /// </summary>
        internal static string ExportDialog_Label_FilterDate {
            get {
                return ResourceManager.GetString("ExportDialog_Label_FilterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Experiment: ähnelt.
        /// </summary>
        internal static string ExportDialog_Label_FilterExperiment {
            get {
                return ResourceManager.GetString("ExportDialog_Label_FilterExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group: ähnelt.
        /// </summary>
        internal static string ExportDialog_Label_FilterGroup {
            get {
                return ResourceManager.GetString("ExportDialog_Label_FilterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string ExportDialog_Label_FilterName {
            get {
                return ResourceManager.GetString("ExportDialog_Label_FilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date of Measurement ähnelt.
        /// </summary>
        internal static string ExportDialog_TextBox_FilterDate_Watermark {
            get {
                return ResourceManager.GetString("ExportDialog_TextBox_FilterDate_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string ExportDialog_TextBox_FilterName_Watermark {
            get {
                return ResourceManager.GetString("ExportDialog_TextBox_FilterName_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a file ähnelt.
        /// </summary>
        internal static string ExportMeasurementxDialog_Title {
            get {
                return ResourceManager.GetString("ExportMeasurementxDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export directory ähnelt.
        /// </summary>
        internal static string ExportOptionsView_ExportPath_Watermark {
            get {
                return ResourceManager.GetString("ExportOptionsView_ExportPath_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export format: ähnelt.
        /// </summary>
        internal static string ExportOptionsView_Label_ExportFormat {
            get {
                return ResourceManager.GetString("ExportOptionsView_Label_ExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export mode: ähnelt.
        /// </summary>
        internal static string ExportOptionsView_Label_ExportOptions {
            get {
                return ResourceManager.GetString("ExportOptionsView_Label_ExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export directory: ähnelt.
        /// </summary>
        internal static string ExportOptionsView_Label_ExportPath {
            get {
                return ResourceManager.GetString("ExportOptionsView_Label_ExportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File name: ähnelt.
        /// </summary>
        internal static string ExportOptionsView_Label_FileName {
            get {
                return ResourceManager.GetString("ExportOptionsView_Label_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One file ähnelt.
        /// </summary>
        internal static string ExportOptionsView_Mode_OneFile {
            get {
                return ResourceManager.GetString("ExportOptionsView_Mode_OneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One file per measurement ähnelt.
        /// </summary>
        internal static string ExportOptionsView_Mode_PerMeasurement {
            get {
                return ResourceManager.GetString("ExportOptionsView_Mode_PerMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CASY internal format (.csy) ähnelt.
        /// </summary>
        internal static string ExportOptionsView_Option_CSY {
            get {
                return ResourceManager.GetString("ExportOptionsView_Option_CSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Raw data (.raw) ähnelt.
        /// </summary>
        internal static string ExportOptionsView_Option_RAW {
            get {
                return ResourceManager.GetString("ExportOptionsView_Option_RAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File name ähnelt.
        /// </summary>
        internal static string ExportOptionsView_TextBox_FileName_Watermark {
            get {
                return ResourceManager.GetString("ExportOptionsView_TextBox_FileName_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export settings: ähnelt.
        /// </summary>
        internal static string ExportOptionsView_Title {
            get {
                return ResourceManager.GetString("ExportOptionsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured trying to open file &apos;{0}&apos;. Please check operating system settings for a standard association for the used file extension. ähnelt.
        /// </summary>
        internal static string FailedToOpenFile_Message {
            get {
                return ResourceManager.GetString("FailedToOpenFile_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to open file ähnelt.
        /// </summary>
        internal static string FailedToOpenFile_Title {
            get {
                return ResourceManager.GetString("FailedToOpenFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please choose a name for the measurement result imported from file &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string ImportCRFDialog_Message {
            get {
                return ResourceManager.GetString("ImportCRFDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measurement Result Name ähnelt.
        /// </summary>
        internal static string ImportCRFDialog_Title {
            get {
                return ResourceManager.GetString("ImportCRFDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imported measurement &apos;{0}&apos; contains audit trail information. This information will be deleted because you version is not CFR21 Part 11 compliant.
        ///Do you want to continue? ähnelt.
        /// </summary>
        internal static string ImportingCfrInNonCfrVersionDialog_Content {
            get {
                return ResourceManager.GetString("ImportingCfrInNonCfrVersionDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measurement with audit trail detected ähnelt.
        /// </summary>
        internal static string ImportingCfrInNonCfrVersionDialog_Title {
            get {
                return ResourceManager.GetString("ImportingCfrInNonCfrVersionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imported measurement &apos;{0}&apos; does not orginate from a CFR compliant software version. The history is not tracable.
        ///Do you want to continue? ähnelt.
        /// </summary>
        internal static string ImportingNonCfrInCfrVersionDialog_Content {
            get {
                return ResourceManager.GetString("ImportingNonCfrInCfrVersionDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Non CFR compliant measurement detected ähnelt.
        /// </summary>
        internal static string ImportingNonCfrInCfrVersionDialog_Title {
            get {
                return ResourceManager.GetString("ImportingNonCfrInCfrVersionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import of template failed. The combination of capillary ({0} µm) and max range ({1} µm) is not valid for this system. ähnelt.
        /// </summary>
        internal static string ImportTemplateFailed_Content {
            get {
                return ResourceManager.GetString("ImportTemplateFailed_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import failed ähnelt.
        /// </summary>
        internal static string ImportTemplateFailed_Title {
            get {
                return ResourceManager.GetString("ImportTemplateFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please ensure the name of the imported file does not contain a semicolon. ähnelt.
        /// </summary>
        internal static string ImportTTError_Content {
            get {
                return ResourceManager.GetString("ImportTTError_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured while importing file ähnelt.
        /// </summary>
        internal static string ImportTTError_Title {
            get {
                return ResourceManager.GetString("ImportTTError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select template for import ähnelt.
        /// </summary>
        internal static string LoadTemplateFileDialog_Title {
            get {
                return ResourceManager.GetString("LoadTemplateFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define data and its order printing a mean diagram. ähnelt.
        /// </summary>
        internal static string MeanDocumentSettings_Title {
            get {
                return ResourceManager.GetString("MeanDocumentSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mean ähnelt.
        /// </summary>
        internal static string MeanDocumentSettingsViewModel_Title {
            get {
                return ResourceManager.GetString("MeanDocumentSettingsViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Concentration: ähnelt.
        /// </summary>
        internal static string MeasureContainerView_Label_Concentration {
            get {
                return ResourceManager.GetString("MeasureContainerView_Label_Concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counts / ml &gt; {0} µm: ähnelt.
        /// </summary>
        internal static string MeasureContainerView_Label_CountsAboveDiamter {
            get {
                return ResourceManager.GetString("MeasureContainerView_Label_CountsAboveDiamter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total Counts ({0} x {1}): ähnelt.
        /// </summary>
        internal static string MeasureContainerView_Label_TotalCounts {
            get {
                return ResourceManager.GetString("MeasureContainerView_Label_TotalCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counts selected range(s): ähnelt.
        /// </summary>
        internal static string MeasureContainerView_Label_TotalCountsCursor {
            get {
                return ResourceManager.GetString("MeasureContainerView_Label_TotalCountsCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Viable cells: ähnelt.
        /// </summary>
        internal static string MeasureContainerView_Label_TotalCountsViability {
            get {
                return ResourceManager.GetString("MeasureContainerView_Label_TotalCountsViability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AGGREGATION: ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Label_Aggregation {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Label_Aggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die COLORS: ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Label_Color {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Label_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DILUTION: ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Label_DilutionFactor {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Label_DilutionFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MODE ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Label_MeasureMode {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Label_MeasureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normalization activ ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Label_Normalize {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Label_Normalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SMOOTHING: ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Label_Smoothing {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Label_Smoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subpopulation ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Label_SubPopulations {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Label_SubPopulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Label_SubPopulationsActive {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Label_SubPopulationsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y-SCALE: ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Label_YScale {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Label_YScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual Value ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_OmniTextBox_ManualAggregationCalculationFactor_Watermark {
            get {
                return ResourceManager.GetString("MeasureResultChartView_OmniTextBox_ManualAggregationCalculationFactor_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MAX. RANGE ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_OmniTextBox_ScalingMaxRange_Watermark {
            get {
                return ResourceManager.GetString("MeasureResultChartView_OmniTextBox_ScalingMaxRange_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Off ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_SmoothingFactor_Off {
            get {
                return ResourceManager.GetString("MeasureResultChartView_SmoothingFactor_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Value_AutoRange {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Value_AutoRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counts ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Value_Counts {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Value_Counts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volume ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Value_Volume {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Value_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diameter (µm) ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_XAxis_Label {
            get {
                return ResourceManager.GetString("MeasureResultChartView_XAxis_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counts ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_YAxis_Label_Counts {
            get {
                return ResourceManager.GetString("MeasureResultChartView_YAxis_Label_Counts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volume x E4 ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_YAxis_Label_Volume {
            get {
                return ResourceManager.GetString("MeasureResultChartView_YAxis_Label_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply changes ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_ApplyToParentsButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_ApplyToParentsButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show audit trail ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_AuditTrailButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_AuditTrailButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_PrintButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_PrintButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore measurement ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_RestoreButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_RestoreButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Store settings as template ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_SaveAsTemplateButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_SaveAsTemplateButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_SaveButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_SaveButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save graph as picture ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_SavePictureButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_SavePictureButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show original settings ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_ShowOriginalButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_ShowOriginalButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show parent measurements ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_ShowParentsButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_ShowParentsButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show / Hide menu ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_ToggleButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_ToggleButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time of measurement ähnelt.
        /// </summary>
        internal static string MeasureResultDataChartViewModel_AxisX_Title {
            get {
                return ResourceManager.GetString("MeasureResultDataChartViewModel_AxisX_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mesaurement value ähnelt.
        /// </summary>
        internal static string MeasureResultDataChartViewModel_AxisY_Title {
            get {
                return ResourceManager.GetString("MeasureResultDataChartViewModel_AxisY_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AGGR. FACTOR ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_AggregationFactor {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_AggregationFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die COMMENT: ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_Comment {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % COUNT ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_CountsPercentage {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_CountsPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die COUNTS / ML ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_CountsPerMl {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_CountsPerMl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ø MEAN ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_MeanDiameter {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_MeanDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RANGE ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_Name {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ø PEAK ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_PeakDiameter {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_PeakDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VOL PEAK ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_PeakVolume {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_PeakVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RANGE SETTINGS ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_RoiSettings {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_RoiSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TOTAL ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_Total {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VIABILITY ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_Viability {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_Viability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CELLS / ML ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_ViableCells {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_ViableCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VOL / ML ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_VolumePerMl {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_VolumePerMl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Select All) ähnelt.
        /// </summary>
        internal static string MeasureResultSubTreeView_Button_SelectAll {
            get {
                return ResourceManager.GetString("MeasureResultSubTreeView_Button_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EXPERIMENTS ähnelt.
        /// </summary>
        internal static string MeasureResultTreeView_BackButton_DefaultText {
            get {
                return ResourceManager.GetString("MeasureResultTreeView_BackButton_DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        internal static string MeasureResultTreeView_BackButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultTreeView_BackButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export measurements ähnelt.
        /// </summary>
        internal static string MeasureResultTreeView_ExportButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultTreeView_ExportButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [No Experiment] ähnelt.
        /// </summary>
        internal static string MeasureResultTreeView_GroupNode_NoExperiment {
            get {
                return ResourceManager.GetString("MeasureResultTreeView_GroupNode_NoExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [No Group] ähnelt.
        /// </summary>
        internal static string MeasureResultTreeView_GroupNode_NoGroup {
            get {
                return ResourceManager.GetString("MeasureResultTreeView_GroupNode_NoGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import measurements ähnelt.
        /// </summary>
        internal static string MeasureResultTreeView_ImportButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultTreeView_ImportButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset selection ähnelt.
        /// </summary>
        internal static string MeasureResultTreeView_RemoveAllFromSelectionButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultTreeView_RemoveAllFromSelectionButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Deleted ähnelt.
        /// </summary>
        internal static string MeasureResultTreeView_ShowDeleted_Label {
            get {
                return ResourceManager.GetString("MeasureResultTreeView_ShowDeleted_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This measurement already exists in system database. How would you like to proceed? ähnelt.
        /// </summary>
        internal static string MeasureResultWithGuidExistsDialog_Content {
            get {
                return ResourceManager.GetString("MeasureResultWithGuidExistsDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This measurement already exists ähnelt.
        /// </summary>
        internal static string MeasureResultWithGuidExistsDialog_Title {
            get {
                return ResourceManager.GetString("MeasureResultWithGuidExistsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dismiss ähnelt.
        /// </summary>
        internal static string MessageBox_Button_ContinueWithoutSave {
            get {
                return ResourceManager.GetString("MessageBox_Button_ContinueWithoutSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save all ähnelt.
        /// </summary>
        internal static string MessageBox_Button_SaveAll {
            get {
                return ResourceManager.GetString("MessageBox_Button_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save All ähnelt.
        /// </summary>
        internal static string MessageBox_Button_SaveAll_Text {
            get {
                return ResourceManager.GetString("MessageBox_Button_SaveAll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}*&apos; has not been saved. 
        ///Continue without saving will dismiss the measurement. ähnelt.
        /// </summary>
        internal static string MessageBox_TemporaryMeasureResultNotSaved_Content {
            get {
                return ResourceManager.GetString("MessageBox_TemporaryMeasureResultNotSaved_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current measurement not stored ähnelt.
        /// </summary>
        internal static string MessageBox_TemporaryMeasureResultNotSaved_Title {
            get {
                return ResourceManager.GetString("MessageBox_TemporaryMeasureResultNotSaved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following parameters of the overlay have been transmitted to the measurements:
        ///- Display options (Smoothing, Y-Axis settings)
        ///- Range settings ähnelt.
        /// </summary>
        internal static string MesureResultContainerViewModel_ApplyToParents_Message {
            get {
                return ResourceManager.GetString("MesureResultContainerViewModel_ApplyToParents_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply To Parents successfull ähnelt.
        /// </summary>
        internal static string MesureResultContainerViewModel_ApplyToParents_Title {
            get {
                return ResourceManager.GetString("MesureResultContainerViewModel_ApplyToParents_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Order now ähnelt.
        /// </summary>
        internal static string Notification_LessCounts_ButtonText {
            get {
                return ResourceManager.GetString("Notification_LessCounts_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You only have {0} counts left. Please consider ordering new counts. ähnelt.
        /// </summary>
        internal static string Notification_LessCounts_Message {
            get {
                return ResourceManager.GetString("Notification_LessCounts_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Less Counts ähnelt.
        /// </summary>
        internal static string Notification_LessCounts_Title {
            get {
                return ResourceManager.GetString("Notification_LessCounts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Order now ähnelt.
        /// </summary>
        internal static string Notification_NoCounts_ButtonText {
            get {
                return ResourceManager.GetString("Notification_NoCounts_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measuring is not possible due to a lack of counts. Please reorder counts. ähnelt.
        /// </summary>
        internal static string Notification_NoCounts_Message {
            get {
                return ResourceManager.GetString("Notification_NoCounts_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No measuring possible ähnelt.
        /// </summary>
        internal static string Notification_NoCounts_Title {
            get {
                return ResourceManager.GetString("Notification_NoCounts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select files you want to open/import. ähnelt.
        /// </summary>
        internal static string OpenImportMeasureResultDialog_Title {
            get {
                return ResourceManager.GetString("OpenImportMeasureResultDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define data and its order printing an overlay diagram. ähnelt.
        /// </summary>
        internal static string OverlayDocumentSettings_Title {
            get {
                return ResourceManager.GetString("OverlayDocumentSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overlay ähnelt.
        /// </summary>
        internal static string OverlayDocumentSettingsViewModel_Title {
            get {
                return ResourceManager.GetString("OverlayDocumentSettingsViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select image export file: ähnelt.
        /// </summary>
        internal static string SaveAsImageDialog_Title {
            get {
                return ResourceManager.GetString("SaveAsImageDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please choose name for new template ähnelt.
        /// </summary>
        internal static string SaveAsTemplateDialog_Content {
            get {
                return ResourceManager.GetString("SaveAsTemplateDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A template with the same name already exists. How do you want to proceed? ähnelt.
        /// </summary>
        internal static string SaveAsTemplateDialog_SetupAlreadyExists_Content {
            get {
                return ResourceManager.GetString("SaveAsTemplateDialog_SetupAlreadyExists_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template with same name already exists ähnelt.
        /// </summary>
        internal static string SaveAsTemplateDialog_SetupAlreadyExists_Title {
            get {
                return ResourceManager.GetString("SaveAsTemplateDialog_SetupAlreadyExists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save measurement parameter as template ähnelt.
        /// </summary>
        internal static string SaveAsTemplateDialog_Title {
            get {
                return ResourceManager.GetString("SaveAsTemplateDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template name ähnelt.
        /// </summary>
        internal static string SaveAsTemplateDialog_Watermark {
            get {
                return ResourceManager.GetString("SaveAsTemplateDialog_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Experiment ähnelt.
        /// </summary>
        internal static string SaveMeasureResultDialog_ComboBox_Experiment_Watermark {
            get {
                return ResourceManager.GetString("SaveMeasureResultDialog_ComboBox_Experiment_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group ähnelt.
        /// </summary>
        internal static string SaveMeasureResultDialog_ComboBox_Group_Watermark {
            get {
                return ResourceManager.GetString("SaveMeasureResultDialog_ComboBox_Group_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comment ähnelt.
        /// </summary>
        internal static string SaveMeasureResultDialog_OmniTextBox_Comment_Watermark {
            get {
                return ResourceManager.GetString("SaveMeasureResultDialog_OmniTextBox_Comment_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measurement Name ähnelt.
        /// </summary>
        internal static string SaveMeasureResultDialog_OmniTextBox_MeasureResultName_Watermark {
            get {
                return ResourceManager.GetString("SaveMeasureResultDialog_OmniTextBox_MeasureResultName_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Measurement Result ähnelt.
        /// </summary>
        internal static string SaveMeasureResultDialog_Title {
            get {
                return ResourceManager.GetString("SaveMeasureResultDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please choose name for new template ähnelt.
        /// </summary>
        internal static string SaveTemplateAsDialog_Content {
            get {
                return ResourceManager.GetString("SaveTemplateAsDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select template name ähnelt.
        /// </summary>
        internal static string SaveTemplateAsDialog_Title {
            get {
                return ResourceManager.GetString("SaveTemplateAsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select file for export ähnelt.
        /// </summary>
        internal static string SaveTemplateFileDialog_Title {
            get {
                return ResourceManager.GetString("SaveTemplateFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available ähnelt.
        /// </summary>
        internal static string SelectMeasurementsView_Header_Available {
            get {
                return ResourceManager.GetString("SelectMeasurementsView_Header_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clustering ähnelt.
        /// </summary>
        internal static string SelectMeasurementsView_Header_Clustering {
            get {
                return ResourceManager.GetString("SelectMeasurementsView_Header_Clustering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected ähnelt.
        /// </summary>
        internal static string SelectMeasurementsView_Header_Selected {
            get {
                return ResourceManager.GetString("SelectMeasurementsView_Header_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select measurements to export: ähnelt.
        /// </summary>
        internal static string SelectMeasurementsView_Title {
            get {
                return ResourceManager.GetString("SelectMeasurementsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available Templates: ähnelt.
        /// </summary>
        internal static string SelectTemplateDialog_Header {
            get {
                return ResourceManager.GetString("SelectTemplateDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cap: ähnelt.
        /// </summary>
        internal static string SelectTemplateView_Label_Capillary {
            get {
                return ResourceManager.GetString("SelectTemplateView_Label_Capillary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dilution: ähnelt.
        /// </summary>
        internal static string SelectTemplateView_Label_Dilution {
            get {
                return ResourceManager.GetString("SelectTemplateView_Label_Dilution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max Ø: ähnelt.
        /// </summary>
        internal static string SelectTemplateView_Label_Range {
            get {
                return ResourceManager.GetString("SelectTemplateView_Label_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Range(s) ähnelt.
        /// </summary>
        internal static string SelectTemplateView_Label_Ranges {
            get {
                return ResourceManager.GetString("SelectTemplateView_Label_Ranges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        internal static string SelectTemplateView_Watermark_Filter {
            get {
                return ResourceManager.GetString("SelectTemplateView_Watermark_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define data and its order printing a singe measurement. ähnelt.
        /// </summary>
        internal static string SingleMeasurementSettings_Title {
            get {
                return ResourceManager.GetString("SingleMeasurementSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comment: ähnelt.
        /// </summary>
        internal static string SingleMeasureResultDocument_Heading_Comment {
            get {
                return ResourceManager.GetString("SingleMeasureResultDocument_Heading_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PARAMETER ähnelt.
        /// </summary>
        internal static string SingleMeasureResultDocument_Heading_Parameter {
            get {
                return ResourceManager.GetString("SingleMeasureResultDocument_Heading_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RESULTS ähnelt.
        /// </summary>
        internal static string SingleMeasureResultDocument_Heading_Results {
            get {
                return ResourceManager.GetString("SingleMeasureResultDocument_Heading_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do not show again ähnelt.
        /// </summary>
        internal static string StnadardWizardStepView_DoNotShowAgain {
            get {
                return ResourceManager.GetString("StnadardWizardStepView_DoNotShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We have fund temporary, unsaved measurements and opened them up for you. Now you have the chance to finally save or dismiss them. ähnelt.
        /// </summary>
        internal static string TemporaryMeasurementsFound_Content {
            get {
                return ResourceManager.GetString("TemporaryMeasurementsFound_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temporary measurement restore ähnelt.
        /// </summary>
        internal static string TemporaryMeasurementsFound_Title {
            get {
                return ResourceManager.GetString("TemporaryMeasurementsFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comment is mendetory ähnelt.
        /// </summary>
        internal static string ValidationError_CommentIsMendetory {
            get {
                return ResourceManager.GetString("ValidationError_CommentIsMendetory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measurement name must be unique within its experiment and group ähnelt.
        /// </summary>
        internal static string ValidationError_MeasureResultNameMustBeUnique {
            get {
                return ResourceManager.GetString("ValidationError_MeasureResultNameMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measurement name must not be empty ähnelt.
        /// </summary>
        internal static string ValidationError_MeasureResultNameMustNotBeEmpty {
            get {
                return ResourceManager.GetString("ValidationError_MeasureResultNameMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measurement name must not contain the following characters: /, \, :, *, &lt;, &gt;, | ähnelt.
        /// </summary>
        internal static string ValidationError_MeasureResultNameMustNotContainSpecialChars {
            get {
                return ResourceManager.GetString("ValidationError_MeasureResultNameMustNotContainSpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string WizardContainerView_CancelButton_Content {
            get {
                return ResourceManager.GetString("WizardContainerView_CancelButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        internal static string WizardContainerView_NextButton_Content {
            get {
                return ResourceManager.GetString("WizardContainerView_NextButton_Content", resourceCulture);
            }
        }
    }
}
