//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLS.Casy.Ui.Core.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings_de_DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLS.Casy.Ui.Core.Assets.Resources.ApplicationStrings_de-DE", typeof(ApplicationStrings_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kommentar eingeben ähnelt.
        /// </summary>
        internal static string AddCommentDialog_Title {
            get {
                return ResourceManager.GetString("AddCommentDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willst du das Messergebnis &apos;{0}&apos; wirklich überschreiben? ähnelt.
        /// </summary>
        internal static string ConfirmOverrideDialog_Message {
            get {
                return ResourceManager.GetString("ConfirmOverrideDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messergebnis überschreiben? ähnelt.
        /// </summary>
        internal static string ConfirmOverrideDialog_Title {
            get {
                return ResourceManager.GetString("ConfirmOverrideDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Messergebnisse &apos;{0}&apos; haben noch ungesicherte Änderungen. Wie willst du mit den Änderungen verfahren? ähnelt.
        /// </summary>
        internal static string ConfirmSaveMeasureResultsOnCloseDialog_Content {
            get {
                return ResourceManager.GetString("ConfirmSaveMeasureResultsOnCloseDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausstehende Änderungen ähnelt.
        /// </summary>
        internal static string ConfirmSaveMeasureResultsOnCloseDialog_Title {
            get {
                return ResourceManager.GetString("ConfirmSaveMeasureResultsOnCloseDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willst du wirklich den ausgewählten Bereich löschen? ähnelt.
        /// </summary>
        internal static string DeleteCursorDialog_Content {
            get {
                return ResourceManager.GetString("DeleteCursorDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bereich löschen ähnelt.
        /// </summary>
        internal static string DeleteCursorDialog_Title {
            get {
                return ResourceManager.GetString("DeleteCursorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bist du dir sicher, dass du das Messergebnis &apos;{0}&apos; löschen willst? ähnelt.
        /// </summary>
        internal static string DeleteMesureResult_ConfirmDialog_Content {
            get {
                return ResourceManager.GetString("DeleteMesureResult_ConfirmDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messergebnis löschen ähnelt.
        /// </summary>
        internal static string DeleteMesureResult_ConfirmDialog_Title {
            get {
                return ResourceManager.GetString("DeleteMesureResult_ConfirmDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du willst die Vorlage mit dem Name &apos;{0}&apos; löschen. Bist du dir sicher, dass du mit der Operation fortfahren wollen? ähnelt.
        /// </summary>
        internal static string DeleteTemplateDialog_Content {
            get {
                return ResourceManager.GetString("DeleteTemplateDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorlage löschen ähnelt.
        /// </summary>
        internal static string DeleteTemplateDialog_Title {
            get {
                return ResourceManager.GetString("DeleteTemplateDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PAGE: ähnelt.
        /// </summary>
        internal static string DocumentBase_Footer_Page {
            get {
                return ResourceManager.GetString("DocumentBase_Footer_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die of ähnelt.
        /// </summary>
        internal static string DocumentBase_Footer_Page_Of {
            get {
                return ResourceManager.GetString("DocumentBase_Footer_Page_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DATE OF PRINT: ähnelt.
        /// </summary>
        internal static string DocumentBase_Footer_PrintDate {
            get {
                return ResourceManager.GetString("DocumentBase_Footer_PrintDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die USER: ähnelt.
        /// </summary>
        internal static string DocumentBase_Footer_User {
            get {
                return ResourceManager.GetString("DocumentBase_Footer_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeige das Datum der letzten erfolgreichen wöchentlichen Reinigung an ähnelt.
        /// </summary>
        internal static string DocumentSettingsView_CfrSection_ShowLastWeeklyClean {
            get {
                return ResourceManager.GetString("DocumentSettingsView_CfrSection_ShowLastWeeklyClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CFR EINSTELLUNGEN ähnelt.
        /// </summary>
        internal static string DocumentSettingsView_CfrSection_Title {
            get {
                return ResourceManager.GetString("DocumentSettingsView_CfrSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selektiertes Logo ähnelt.
        /// </summary>
        internal static string DocumentSettingsView_DocumentLogo_Watermark {
            get {
                return ResourceManager.GetString("DocumentSettingsView_DocumentLogo_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DOKUMENTENLOGO ähnelt.
        /// </summary>
        internal static string DocumentSettingsView_LogoSection_Title {
            get {
                return ResourceManager.GetString("DocumentSettingsView_LogoSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audit Trail ähnelt.
        /// </summary>
        internal static string EditTemplateDialog_Button_AuditTrail {
            get {
                return ResourceManager.GetString("EditTemplateDialog_Button_AuditTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EXPORTIEREN ähnelt.
        /// </summary>
        internal static string EditTemplateDialog_Button_Export {
            get {
                return ResourceManager.GetString("EditTemplateDialog_Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IMPORTIEREN ähnelt.
        /// </summary>
        internal static string EditTemplateDialog_Button_Import {
            get {
                return ResourceManager.GetString("EditTemplateDialog_Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SPEICHERN ähnelt.
        /// </summary>
        internal static string EditTemplateDialog_Button_Save {
            get {
                return ResourceManager.GetString("EditTemplateDialog_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kopie speichern ähnelt.
        /// </summary>
        internal static string EditTemplateDialog_Button_SaveAs {
            get {
                return ResourceManager.GetString("EditTemplateDialog_Button_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorlagen bearbeiten: ähnelt.
        /// </summary>
        internal static string EditTemplateDialog_Header {
            get {
                return ResourceManager.GetString("EditTemplateDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KAPILLARE ähnelt.
        /// </summary>
        internal static string EditTemplateView_ComboBox_Capillary_Watermark {
            get {
                return ResourceManager.GetString("EditTemplateView_ComboBox_Capillary_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Experiment ähnelt.
        /// </summary>
        internal static string EditTemplateView_ComboBox_Experiment_Watermark {
            get {
                return ResourceManager.GetString("EditTemplateView_ComboBox_Experiment_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gruppe ähnelt.
        /// </summary>
        internal static string EditTemplateView_ComboBox_Group_Watermark {
            get {
                return ResourceManager.GetString("EditTemplateView_ComboBox_Group_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X-ACHSE ähnelt.
        /// </summary>
        internal static string EditTemplateView_ComboBox_ToDiameter_Watermark {
            get {
                return ResourceManager.GetString("EditTemplateView_ComboBox_ToDiameter_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AGGREGATION: ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_Aggregation {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_Aggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KOMMENTAR ERFORDERLICH ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_AutoComment {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_AutoComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ERZWINGE AUTOSPEICHERUNG ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_AutoSave {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ZYKLEN ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_Counts {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_Counts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ABWEICHUNGSKONTROLLZYKLEN: ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_DeviationControl {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_DeviationControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VERDÜNNUNG ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_Dilution {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_Dilution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MODUS ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_MeasureMode {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_MeasureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GLÄTTUNG: ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_Smoothing {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_Smoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VOLUMEN ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_Volume {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y-ACHSE: ähnelt.
        /// </summary>
        internal static string EditTemplateView_Label_YScale {
            get {
                return ResourceManager.GetString("EditTemplateView_Label_YScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die STANDARD NAME ähnelt.
        /// </summary>
        internal static string EditTemplateView_OmniTextBox_AutoSaveName_Watermark {
            get {
                return ResourceManager.GetString("EditTemplateView_OmniTextBox_AutoSaveName_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manueller Wert ähnelt.
        /// </summary>
        internal static string EditTemplateView_OmniTextBox_ManualAggregationCalculationFactor_Watermark {
            get {
                return ResourceManager.GetString("EditTemplateView_OmniTextBox_ManualAggregationCalculationFactor_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorlagenname ähnelt.
        /// </summary>
        internal static string EditTemplateView_OmniTextBox_Name_Watermark {
            get {
                return ResourceManager.GetString("EditTemplateView_OmniTextBox_Name_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MAX. RANGE ähnelt.
        /// </summary>
        internal static string EditTemplateView_OmniTextBox_ScalingMaxRange_Watermark {
            get {
                return ResourceManager.GetString("EditTemplateView_OmniTextBox_ScalingMaxRange_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto ähnelt.
        /// </summary>
        internal static string EditTemplateView_Value_AutoRange {
            get {
                return ResourceManager.GetString("EditTemplateView_Value_AutoRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl ähnelt.
        /// </summary>
        internal static string EditTemplateView_Value_Counts {
            get {
                return ResourceManager.GetString("EditTemplateView_Value_Counts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volumen ähnelt.
        /// </summary>
        internal static string EditTemplateView_Value_Volume {
            get {
                return ResourceManager.GetString("EditTemplateView_Value_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Achtung! Änderung dieser Vorlageneinstellung setzt die definierten Bereiche zurück. ähnelt.
        /// </summary>
        internal static string EditTemplateViewModel_ResetCursorMessage_Message {
            get {
                return ResourceManager.GetString("EditTemplateViewModel_ResetCursorMessage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ranges werden zurückgesetzt ähnelt.
        /// </summary>
        internal static string EditTemplateViewModel_ResetCursorMessage_Title {
            get {
                return ResourceManager.GetString("EditTemplateViewModel_ResetCursorMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportieren ähnelt.
        /// </summary>
        internal static string ExportDialog_Button_Export {
            get {
                return ResourceManager.GetString("ExportDialog_Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiter ähnelt.
        /// </summary>
        internal static string ExportDialog_Button_Next {
            get {
                return ResourceManager.GetString("ExportDialog_Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Experiment ähnelt.
        /// </summary>
        internal static string ExportDialog_ComboBox_Experiment_Watermark {
            get {
                return ResourceManager.GetString("ExportDialog_ComboBox_Experiment_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gruppe ähnelt.
        /// </summary>
        internal static string ExportDialog_ComboBox_Group_Watermark {
            get {
                return ResourceManager.GetString("ExportDialog_ComboBox_Group_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messdatum: ähnelt.
        /// </summary>
        internal static string ExportDialog_Label_FilterDate {
            get {
                return ResourceManager.GetString("ExportDialog_Label_FilterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Experiment: ähnelt.
        /// </summary>
        internal static string ExportDialog_Label_FilterExperiment {
            get {
                return ResourceManager.GetString("ExportDialog_Label_FilterExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gruppe: ähnelt.
        /// </summary>
        internal static string ExportDialog_Label_FilterGroup {
            get {
                return ResourceManager.GetString("ExportDialog_Label_FilterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string ExportDialog_Label_FilterName {
            get {
                return ResourceManager.GetString("ExportDialog_Label_FilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messdatum ähnelt.
        /// </summary>
        internal static string ExportDialog_TextBox_FilterDate_Watermark {
            get {
                return ResourceManager.GetString("ExportDialog_TextBox_FilterDate_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string ExportDialog_TextBox_FilterName_Watermark {
            get {
                return ResourceManager.GetString("ExportDialog_TextBox_FilterName_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wähle eine Datei ähnelt.
        /// </summary>
        internal static string ExportMeasurementxDialog_Title {
            get {
                return ResourceManager.GetString("ExportMeasurementxDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportverzeichnis ähnelt.
        /// </summary>
        internal static string ExportOptionsView_ExportPath_Watermark {
            get {
                return ResourceManager.GetString("ExportOptionsView_ExportPath_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportformat: ähnelt.
        /// </summary>
        internal static string ExportOptionsView_Label_ExportFormat {
            get {
                return ResourceManager.GetString("ExportOptionsView_Label_ExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportmodus: ähnelt.
        /// </summary>
        internal static string ExportOptionsView_Label_ExportOptions {
            get {
                return ResourceManager.GetString("ExportOptionsView_Label_ExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportverzeichnis: ähnelt.
        /// </summary>
        internal static string ExportOptionsView_Label_ExportPath {
            get {
                return ResourceManager.GetString("ExportOptionsView_Label_ExportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateiname: ähnelt.
        /// </summary>
        internal static string ExportOptionsView_Label_FileName {
            get {
                return ResourceManager.GetString("ExportOptionsView_Label_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine Datei ähnelt.
        /// </summary>
        internal static string ExportOptionsView_Mode_OneFile {
            get {
                return ResourceManager.GetString("ExportOptionsView_Mode_OneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine Datei pro Messung ähnelt.
        /// </summary>
        internal static string ExportOptionsView_Mode_PerMeasurement {
            get {
                return ResourceManager.GetString("ExportOptionsView_Mode_PerMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CASY internes Format (.csy) ähnelt.
        /// </summary>
        internal static string ExportOptionsView_Option_CSY {
            get {
                return ResourceManager.GetString("ExportOptionsView_Option_CSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rohdaten (.raw) ähnelt.
        /// </summary>
        internal static string ExportOptionsView_Option_RAW {
            get {
                return ResourceManager.GetString("ExportOptionsView_Option_RAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateiname ähnelt.
        /// </summary>
        internal static string ExportOptionsView_TextBox_FileName_Watermark {
            get {
                return ResourceManager.GetString("ExportOptionsView_TextBox_FileName_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen für den Export: ähnelt.
        /// </summary>
        internal static string ExportOptionsView_Title {
            get {
                return ResourceManager.GetString("ExportOptionsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein Fehler beim Öffnen der Datei &apos;{0}&apos; aufgetreten. Bitte überprüfen Sie in den Einstellungen des Betriebsystems, ob eine Standard-Zuordnung für die Dateiendung gesetzt ist. ähnelt.
        /// </summary>
        internal static string FailedToOpenFile_Message {
            get {
                return ResourceManager.GetString("FailedToOpenFile_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei konnte nicht geöffnet werden ähnelt.
        /// </summary>
        internal static string FailedToOpenFile_Title {
            get {
                return ResourceManager.GetString("FailedToOpenFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wähle einen Namen für das Messergebnis aus der Datei &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string ImportCRFDialog_Message {
            get {
                return ResourceManager.GetString("ImportCRFDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messergebnis benennen ähnelt.
        /// </summary>
        internal static string ImportCRFDialog_Title {
            get {
                return ResourceManager.GetString("ImportCRFDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die importierte Messung &apos;{0}&apos; enthält Audit-Trail-Informationen. Diese werden entfernt, da deine Software-Version nicht CFR 21 Part 11 konform ist.
        ///Möchtest du fortfahren? ähnelt.
        /// </summary>
        internal static string ImportingCfrInNonCfrVersionDialog_Content {
            get {
                return ResourceManager.GetString("ImportingCfrInNonCfrVersionDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messung mit Audit-Trail-Informationen entdeckt ähnelt.
        /// </summary>
        internal static string ImportingCfrInNonCfrVersionDialog_Title {
            get {
                return ResourceManager.GetString("ImportingCfrInNonCfrVersionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die importierte Messsung &apos;{0}&apos; stammt aus einer nicht CFR-konformen Software-Version. Die Historie der Messung ist damit nicht komplett nachverfolgbar.
        ///Möchtest du denoch fortfahren? ähnelt.
        /// </summary>
        internal static string ImportingNonCfrInCfrVersionDialog_Content {
            get {
                return ResourceManager.GetString("ImportingNonCfrInCfrVersionDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht CFR-konforme Messung entdeckt ähnelt.
        /// </summary>
        internal static string ImportingNonCfrInCfrVersionDialog_Title {
            get {
                return ResourceManager.GetString("ImportingNonCfrInCfrVersionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Import der Vorlage ist fehlgeschlagen. Die Kombination aus Kapillare ({0} µm) und maximalem Durchmesser ({1} µm) wird vom System nicht unterstützt. ähnelt.
        /// </summary>
        internal static string ImportTemplateFailed_Content {
            get {
                return ResourceManager.GetString("ImportTemplateFailed_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Importieren fehlgeschlagen ähnelt.
        /// </summary>
        internal static string ImportTemplateFailed_Title {
            get {
                return ResourceManager.GetString("ImportTemplateFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte stelle sicher, dass der Name der importierten Datei kein Semikolon enthält ähnelt.
        /// </summary>
        internal static string ImportTTError_Content {
            get {
                return ResourceManager.GetString("ImportTTError_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Fehler ist beim Import aufgetreten ähnelt.
        /// </summary>
        internal static string ImportTTError_Title {
            get {
                return ResourceManager.GetString("ImportTTError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zu importierende Vorlage auswählen: ähnelt.
        /// </summary>
        internal static string LoadTemplateFileDialog_Title {
            get {
                return ResourceManager.GetString("LoadTemplateFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Definiere hier, welche Daten in welcher Reihenfolge beim Drucken einer Mean-Kurve verwendet werden. ähnelt.
        /// </summary>
        internal static string MeanDocumentSettings_Title {
            get {
                return ResourceManager.GetString("MeanDocumentSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mittelwert ähnelt.
        /// </summary>
        internal static string MeanDocumentSettingsViewModel_Title {
            get {
                return ResourceManager.GetString("MeanDocumentSettingsViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konzentration: ähnelt.
        /// </summary>
        internal static string MeasureContainerView_Label_Concentration {
            get {
                return ResourceManager.GetString("MeasureContainerView_Label_Concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl / ml &gt; {0} µm: ähnelt.
        /// </summary>
        internal static string MeasureContainerView_Label_CountsAboveDiamter {
            get {
                return ResourceManager.GetString("MeasureContainerView_Label_CountsAboveDiamter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gesamtanzahl ({0} x {1}): ähnelt.
        /// </summary>
        internal static string MeasureContainerView_Label_TotalCounts {
            get {
                return ResourceManager.GetString("MeasureContainerView_Label_TotalCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gesamtanzahl ausgewählte Bereiche: ähnelt.
        /// </summary>
        internal static string MeasureContainerView_Label_TotalCountsCursor {
            get {
                return ResourceManager.GetString("MeasureContainerView_Label_TotalCountsCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Viable Zellen: ähnelt.
        /// </summary>
        internal static string MeasureContainerView_Label_TotalCountsViability {
            get {
                return ResourceManager.GetString("MeasureContainerView_Label_TotalCountsViability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breiech hinzufügen ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_AddRangeButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultChartView_AddRangeButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zugriffsrechte verwalten ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_EditAccessButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultChartView_EditAccessButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AGGREGATION: ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Label_Aggregation {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Label_Aggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FARBEN: ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Label_Color {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Label_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VERDÜNNUNG: ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Label_DilutionFactor {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Label_DilutionFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MODUS ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Label_MeasureMode {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Label_MeasureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normalisierung aktiv ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Label_Normalize {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Label_Normalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GLÄTTUNG: ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Label_Smoothing {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Label_Smoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subpopulation ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Label_SubPopulations {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Label_SubPopulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Label_SubPopulationsActive {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Label_SubPopulationsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y-ACHSE: ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Label_YScale {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Label_YScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manueller Wert ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_OmniTextBox_ManualAggregationCalculationFactor_Watermark {
            get {
                return ResourceManager.GetString("MeasureResultChartView_OmniTextBox_ManualAggregationCalculationFactor_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MAX. RANGE ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_OmniTextBox_ScalingMaxRange_Watermark {
            get {
                return ResourceManager.GetString("MeasureResultChartView_OmniTextBox_ScalingMaxRange_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_SettingsButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultChartView_SettingsButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aus ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_SmoothingFactor_Off {
            get {
                return ResourceManager.GetString("MeasureResultChartView_SmoothingFactor_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Value_AutoRange {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Value_AutoRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Value_Counts {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Value_Counts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volumen ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_Value_Volume {
            get {
                return ResourceManager.GetString("MeasureResultChartView_Value_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Durchmesser (µm) ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_XAxis_Label {
            get {
                return ResourceManager.GetString("MeasureResultChartView_XAxis_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_YAxis_Label_Counts {
            get {
                return ResourceManager.GetString("MeasureResultChartView_YAxis_Label_Counts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volumen x E4 ähnelt.
        /// </summary>
        internal static string MeasureResultChartView_YAxis_Label_Volume {
            get {
                return ResourceManager.GetString("MeasureResultChartView_YAxis_Label_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen übertragen ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_ApplyToParentsButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_ApplyToParentsButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audit Trail anzeigen ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_AuditTrailButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_AuditTrailButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drucken ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_PrintButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_PrintButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messung Wiederherstellen ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_RestoreButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_RestoreButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen als Template speichern ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_SaveAsTemplateButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_SaveAsTemplateButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_SaveButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_SaveButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Graph als Bild speichern ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_SavePictureButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_SavePictureButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messung mit Originaleinstellungen anzeigen ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_ShowOriginalButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_ShowOriginalButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elternmessungen ein-/ausblenden ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_ShowParentsButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_ShowParentsButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein-/Ausblenden ähnelt.
        /// </summary>
        internal static string MeasureResultContainerView_ToggleButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultContainerView_ToggleButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeitpunkt der Messung ähnelt.
        /// </summary>
        internal static string MeasureResultDataChartViewModel_AxisX_Title {
            get {
                return ResourceManager.GetString("MeasureResultDataChartViewModel_AxisX_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messwert ähnelt.
        /// </summary>
        internal static string MeasureResultDataChartViewModel_AxisY_Title {
            get {
                return ResourceManager.GetString("MeasureResultDataChartViewModel_AxisY_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AGGR. FAKTOR ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_AggregationFactor {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_AggregationFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KOMMENTAR: ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_Comment {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % ANZAHL ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_CountsPercentage {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_CountsPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ANZAHL / ML ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_CountsPerMl {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_CountsPerMl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ø MITTEL ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_MeanDiameter {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_MeanDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BEREICH ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_Name {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ø PEAK ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_PeakDiameter {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_PeakDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VOL PEAK ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_PeakVolume {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_PeakVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EINSTELLUNGEN BEREICHE ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_RoiSettings {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_RoiSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GESAMT ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_Total {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VIABILITÄT ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_Viability {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_Viability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ZELLZAHL / ML ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_ViableCells {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_ViableCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VOL / ML ähnelt.
        /// </summary>
        internal static string MeasureResultDataView_Label_VolumePerMl {
            get {
                return ResourceManager.GetString("MeasureResultDataView_Label_VolumePerMl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Alle Auswählen) ähnelt.
        /// </summary>
        internal static string MeasureResultSubTreeView_Button_SelectAll {
            get {
                return ResourceManager.GetString("MeasureResultSubTreeView_Button_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EXPERIMENTE ähnelt.
        /// </summary>
        internal static string MeasureResultTreeView_BackButton_DefaultText {
            get {
                return ResourceManager.GetString("MeasureResultTreeView_BackButton_DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurück ähnelt.
        /// </summary>
        internal static string MeasureResultTreeView_BackButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultTreeView_BackButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messergebnisse exportieren ähnelt.
        /// </summary>
        internal static string MeasureResultTreeView_ExportButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultTreeView_ExportButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [Kein Experiment] ähnelt.
        /// </summary>
        internal static string MeasureResultTreeView_GroupNode_NoExperiment {
            get {
                return ResourceManager.GetString("MeasureResultTreeView_GroupNode_NoExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [Keine Gruppe] ähnelt.
        /// </summary>
        internal static string MeasureResultTreeView_GroupNode_NoGroup {
            get {
                return ResourceManager.GetString("MeasureResultTreeView_GroupNode_NoGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messergebnisse importieren ähnelt.
        /// </summary>
        internal static string MeasureResultTreeView_ImportButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultTreeView_ImportButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auwahl zurücksetzen ähnelt.
        /// </summary>
        internal static string MeasureResultTreeView_RemoveAllFromSelectionButton_Tooltip {
            get {
                return ResourceManager.GetString("MeasureResultTreeView_RemoveAllFromSelectionButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gelöschte anzeigen ähnelt.
        /// </summary>
        internal static string MeasureResultTreeView_ShowDeleted_Label {
            get {
                return ResourceManager.GetString("MeasureResultTreeView_ShowDeleted_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieses Messergebnis existiert bereits in der Systemdatanbank. Wie willst du mit dem Messergebnis fortfahren? ähnelt.
        /// </summary>
        internal static string MeasureResultWithGuidExistsDialog_Content {
            get {
                return ResourceManager.GetString("MeasureResultWithGuidExistsDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messergebnis existiert bereits ähnelt.
        /// </summary>
        internal static string MeasureResultWithGuidExistsDialog_Title {
            get {
                return ResourceManager.GetString("MeasureResultWithGuidExistsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verwerfen ähnelt.
        /// </summary>
        internal static string MessageBox_Button_ContinueWithoutSave {
            get {
                return ResourceManager.GetString("MessageBox_Button_ContinueWithoutSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Speichern ähnelt.
        /// </summary>
        internal static string MessageBox_Button_SaveAll {
            get {
                return ResourceManager.GetString("MessageBox_Button_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Speichern ähnelt.
        /// </summary>
        internal static string MessageBox_Button_SaveAll_Text {
            get {
                return ResourceManager.GetString("MessageBox_Button_SaveAll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}*&apos; wurde bisher nicht gespeichert. 
        ///Fortfahren ohne zu speichern verwirft das aktuelle Messergebnis. ähnelt.
        /// </summary>
        internal static string MessageBox_TemporaryMeasureResultNotSaved_Content {
            get {
                return ResourceManager.GetString("MessageBox_TemporaryMeasureResultNotSaved_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das aktuelle Messergebnis wurde nicht gespeichert ähnelt.
        /// </summary>
        internal static string MessageBox_TemporaryMeasureResultNotSaved_Title {
            get {
                return ResourceManager.GetString("MessageBox_TemporaryMeasureResultNotSaved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folgende Parameter des Overlay wurden auf die einzelnen Messungen übertragen.
        ///- Visuelle Paramter (Glättung, Einstellungen der Y-Achse)
        ///- Bereichsoptionen ähnelt.
        /// </summary>
        internal static string MesureResultContainerViewModel_ApplyToParents_Message {
            get {
                return ResourceManager.GetString("MesureResultContainerViewModel_ApplyToParents_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übernahme erfolgreich ähnelt.
        /// </summary>
        internal static string MesureResultContainerViewModel_ApplyToParents_Title {
            get {
                return ResourceManager.GetString("MesureResultContainerViewModel_ApplyToParents_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jetzt bestellen ähnelt.
        /// </summary>
        internal static string Notification_LessCounts_ButtonText {
            get {
                return ResourceManager.GetString("Notification_LessCounts_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast nur noch {0} Messungen übrig. Überlege dir, neue Messungen zu bestellen. ähnelt.
        /// </summary>
        internal static string Notification_LessCounts_Message {
            get {
                return ResourceManager.GetString("Notification_LessCounts_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wenige Messungen übrig ähnelt.
        /// </summary>
        internal static string Notification_LessCounts_Title {
            get {
                return ResourceManager.GetString("Notification_LessCounts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jetzt bestellen ähnelt.
        /// </summary>
        internal static string Notification_NoCounts_ButtonText {
            get {
                return ResourceManager.GetString("Notification_NoCounts_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Messen ist nicht mehr möglich, da keine Messungen mehr freigeschaltet sind. Bitte bestelle jetzt neue Messungen. ähnelt.
        /// </summary>
        internal static string Notification_NoCounts_Message {
            get {
                return ResourceManager.GetString("Notification_NoCounts_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messen nicht mehr möglich ähnelt.
        /// </summary>
        internal static string Notification_NoCounts_Title {
            get {
                return ResourceManager.GetString("Notification_NoCounts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle die Dateien, die du öffnen/importieren willst. ähnelt.
        /// </summary>
        internal static string OpenImportMeasureResultDialog_Title {
            get {
                return ResourceManager.GetString("OpenImportMeasureResultDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Definiere hier, welche Daten in welcher Reihenfolge beim Drucken einer Overlay-Kurve verwendet werden. ähnelt.
        /// </summary>
        internal static string OverlayDocumentSettings_Title {
            get {
                return ResourceManager.GetString("OverlayDocumentSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overlay ähnelt.
        /// </summary>
        internal static string OverlayDocumentSettingsViewModel_Title {
            get {
                return ResourceManager.GetString("OverlayDocumentSettingsViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bild Export Datei wählen: ähnelt.
        /// </summary>
        internal static string SaveAsImageDialog_Title {
            get {
                return ResourceManager.GetString("SaveAsImageDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wähle einen Namen für die neue Vorlage ähnelt.
        /// </summary>
        internal static string SaveAsTemplateDialog_Content {
            get {
                return ResourceManager.GetString("SaveAsTemplateDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine Vorlage mit dem selben Namen existiert bereits. Wie willst du fortfahren? ähnelt.
        /// </summary>
        internal static string SaveAsTemplateDialog_SetupAlreadyExists_Content {
            get {
                return ResourceManager.GetString("SaveAsTemplateDialog_SetupAlreadyExists_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine Vorlage mit dem selben Namen existiert bereits ähnelt.
        /// </summary>
        internal static string SaveAsTemplateDialog_SetupAlreadyExists_Title {
            get {
                return ResourceManager.GetString("SaveAsTemplateDialog_SetupAlreadyExists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verwendete Messparameter als Vorlage speichern ähnelt.
        /// </summary>
        internal static string SaveAsTemplateDialog_Title {
            get {
                return ResourceManager.GetString("SaveAsTemplateDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorlagenname ähnelt.
        /// </summary>
        internal static string SaveAsTemplateDialog_Watermark {
            get {
                return ResourceManager.GetString("SaveAsTemplateDialog_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Experiment ähnelt.
        /// </summary>
        internal static string SaveMeasureResultDialog_ComboBox_Experiment_Watermark {
            get {
                return ResourceManager.GetString("SaveMeasureResultDialog_ComboBox_Experiment_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gruppe ähnelt.
        /// </summary>
        internal static string SaveMeasureResultDialog_ComboBox_Group_Watermark {
            get {
                return ResourceManager.GetString("SaveMeasureResultDialog_ComboBox_Group_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kommentar ähnelt.
        /// </summary>
        internal static string SaveMeasureResultDialog_OmniTextBox_Comment_Watermark {
            get {
                return ResourceManager.GetString("SaveMeasureResultDialog_OmniTextBox_Comment_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name der Messung ähnelt.
        /// </summary>
        internal static string SaveMeasureResultDialog_OmniTextBox_MeasureResultName_Watermark {
            get {
                return ResourceManager.GetString("SaveMeasureResultDialog_OmniTextBox_MeasureResultName_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messung speichern ähnelt.
        /// </summary>
        internal static string SaveMeasureResultDialog_Title {
            get {
                return ResourceManager.GetString("SaveMeasureResultDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wähle einen Namen für die neue Vorlage ähnelt.
        /// </summary>
        internal static string SaveTemplateAsDialog_Content {
            get {
                return ResourceManager.GetString("SaveTemplateAsDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorlagennamen wählen ähnelt.
        /// </summary>
        internal static string SaveTemplateAsDialog_Title {
            get {
                return ResourceManager.GetString("SaveTemplateAsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei für Export auswählen ähnelt.
        /// </summary>
        internal static string SaveTemplateFileDialog_Title {
            get {
                return ResourceManager.GetString("SaveTemplateFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verfügbar ähnelt.
        /// </summary>
        internal static string SelectMeasurementsView_Header_Available {
            get {
                return ResourceManager.GetString("SelectMeasurementsView_Header_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        internal static string SelectMeasurementsView_Header_Clustering {
            get {
                return ResourceManager.GetString("SelectMeasurementsView_Header_Clustering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgewählt ähnelt.
        /// </summary>
        internal static string SelectMeasurementsView_Header_Selected {
            get {
                return ResourceManager.GetString("SelectMeasurementsView_Header_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle die zu exportierenden Messungen aus: ähnelt.
        /// </summary>
        internal static string SelectMeasurementsView_Title {
            get {
                return ResourceManager.GetString("SelectMeasurementsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verfügbare Vorlagen: ähnelt.
        /// </summary>
        internal static string SelectTemplateDialog_Header {
            get {
                return ResourceManager.GetString("SelectTemplateDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kap: ähnelt.
        /// </summary>
        internal static string SelectTemplateView_Label_Capillary {
            get {
                return ResourceManager.GetString("SelectTemplateView_Label_Capillary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verdünnung: ähnelt.
        /// </summary>
        internal static string SelectTemplateView_Label_Dilution {
            get {
                return ResourceManager.GetString("SelectTemplateView_Label_Dilution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max Ø: ähnelt.
        /// </summary>
        internal static string SelectTemplateView_Label_Range {
            get {
                return ResourceManager.GetString("SelectTemplateView_Label_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bereich(e) ähnelt.
        /// </summary>
        internal static string SelectTemplateView_Label_Ranges {
            get {
                return ResourceManager.GetString("SelectTemplateView_Label_Ranges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        internal static string SelectTemplateView_Watermark_Filter {
            get {
                return ResourceManager.GetString("SelectTemplateView_Watermark_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Definiere hier, welche Daten in welcher Reihenfolge beim Drucken einer Einzelmessung verwendet werden. ähnelt.
        /// </summary>
        internal static string SingleMeasurementSettings_Title {
            get {
                return ResourceManager.GetString("SingleMeasurementSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comment: ähnelt.
        /// </summary>
        internal static string SingleMeasureResultDocument_Heading_Comment {
            get {
                return ResourceManager.GetString("SingleMeasureResultDocument_Heading_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PARAMETER ähnelt.
        /// </summary>
        internal static string SingleMeasureResultDocument_Heading_Parameter {
            get {
                return ResourceManager.GetString("SingleMeasureResultDocument_Heading_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RESULTS ähnelt.
        /// </summary>
        internal static string SingleMeasureResultDocument_Heading_Results {
            get {
                return ResourceManager.GetString("SingleMeasureResultDocument_Heading_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht wieder anzeigen ähnelt.
        /// </summary>
        internal static string StnadardWizardStepView_DoNotShowAgain {
            get {
                return ResourceManager.GetString("StnadardWizardStepView_DoNotShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wir haben ungespeicherte Messungen gefunden. Wir haben diese für dich wiederhergestellt um diese endgültig zu speichern oder zu verwerfen. ähnelt.
        /// </summary>
        internal static string TemporaryMeasurementsFound_Content {
            get {
                return ResourceManager.GetString("TemporaryMeasurementsFound_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wiederherstellung ungespeicherter Messungen ähnelt.
        /// </summary>
        internal static string TemporaryMeasurementsFound_Title {
            get {
                return ResourceManager.GetString("TemporaryMeasurementsFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Kommentar ist erforderlich ähnelt.
        /// </summary>
        internal static string ValidationError_CommentIsMendetory {
            get {
                return ResourceManager.GetString("ValidationError_CommentIsMendetory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Name eines Messergebnis muss innerhalb des Experiment und Gruppe eindeutig sein ähnelt.
        /// </summary>
        internal static string ValidationError_MeasureResultNameMustBeUnique {
            get {
                return ResourceManager.GetString("ValidationError_MeasureResultNameMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Name eines Messergebnis darf nicht leer sein ähnelt.
        /// </summary>
        internal static string ValidationError_MeasureResultNameMustNotBeEmpty {
            get {
                return ResourceManager.GetString("ValidationError_MeasureResultNameMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Name eines Messergebnis darf folgende Zeichen nicht enthalten: /, \, :, *, &lt;, &gt;, | ähnelt.
        /// </summary>
        internal static string ValidationError_MeasureResultNameMustNotContainSpecialChars {
            get {
                return ResourceManager.GetString("ValidationError_MeasureResultNameMustNotContainSpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        internal static string WizardContainerView_CancelButton_Content {
            get {
                return ResourceManager.GetString("WizardContainerView_CancelButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiter ähnelt.
        /// </summary>
        internal static string WizardContainerView_NextButton_Content {
            get {
                return ResourceManager.GetString("WizardContainerView_NextButton_Content", resourceCulture);
            }
        }
    }
}
