//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLS.Casy.Ui.Measure.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings_en_US() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLS.Casy.Ui.Measure.Assets.Resources.ApplicationStrings_en-US", typeof(ApplicationStrings_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the name of the new measurement ähnelt.
        /// </summary>
        internal static string EnterMeasurementName_Content {
            get {
                return ResourceManager.GetString("EnterMeasurementName_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measurement Name ähnelt.
        /// </summary>
        internal static string EnterMeasurementName_Title {
            get {
                return ResourceManager.GetString("EnterMeasurementName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAPILLARY ähnelt.
        /// </summary>
        internal static string ManualMeasurementView_ComboBox_Capillary_Watermark {
            get {
                return ResourceManager.GetString("ManualMeasurementView_ComboBox_Capillary_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X-RANGE ähnelt.
        /// </summary>
        internal static string ManualMeasurementView_ComboBox_ToDiameter_Watermark {
            get {
                return ResourceManager.GetString("ManualMeasurementView_ComboBox_ToDiameter_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select the required parameter for the measurement: ähnelt.
        /// </summary>
        internal static string ManualMeasurementView_Header {
            get {
                return ResourceManager.GetString("ManualMeasurementView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CYCLES ähnelt.
        /// </summary>
        internal static string ManualMeasurementView_Label_Counts {
            get {
                return ResourceManager.GetString("ManualMeasurementView_Label_Counts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DILUTION ähnelt.
        /// </summary>
        internal static string ManualMeasurementView_Label_Dilution {
            get {
                return ResourceManager.GetString("ManualMeasurementView_Label_Dilution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MODE ähnelt.
        /// </summary>
        internal static string ManualMeasurementView_Label_MeasureMode {
            get {
                return ResourceManager.GetString("ManualMeasurementView_Label_MeasureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VOLUME ähnelt.
        /// </summary>
        internal static string ManualMeasurementView_Label_Volume {
            get {
                return ResourceManager.GetString("ManualMeasurementView_Label_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual Measurement ähnelt.
        /// </summary>
        internal static string StartMeasureDialog_Button_ManualMesurement {
            get {
                return ResourceManager.GetString("StartMeasureDialog_Button_ManualMesurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MEASURE ähnelt.
        /// </summary>
        internal static string StartMeasureDialog_Button_Measure {
            get {
                return ResourceManager.GetString("StartMeasureDialog_Button_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Template ähnelt.
        /// </summary>
        internal static string StartMeasureDialog_Button_SelectTemplate {
            get {
                return ResourceManager.GetString("StartMeasureDialog_Button_SelectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select template: ähnelt.
        /// </summary>
        internal static string StartMeasureDialog_Title {
            get {
                return ResourceManager.GetString("StartMeasureDialog_Title", resourceCulture);
            }
        }
    }
}
