//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLS.Casy.Ui.Authorization.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings_en_US() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLS.Casy.Ui.Authorization.Assets.Resources.ApplicationStrings_en-US", typeof(ApplicationStrings_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have to restart the software to apply the change of the display language ähnelt.
        /// </summary>
        internal static string ChangeLanguageInfo_Content {
            get {
                return ResourceManager.GetString("ChangeLanguageInfo_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart of the software required ähnelt.
        /// </summary>
        internal static string ChangeLanguageInfo_Title {
            get {
                return ResourceManager.GetString("ChangeLanguageInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are about to delete user &apos;{0}&apos;. Please confirm you want to continue. ähnelt.
        /// </summary>
        internal static string DeleteUsersDialog_Content {
            get {
                return ResourceManager.GetString("DeleteUsersDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete user ähnelt.
        /// </summary>
        internal static string DeleteUsersDialog_Title {
            get {
                return ResourceManager.GetString("DeleteUsersDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Groups ähnelt.
        /// </summary>
        internal static string GroupManagementView_Button_Toggle {
            get {
                return ResourceManager.GetString("GroupManagementView_Button_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Group Management ähnelt.
        /// </summary>
        internal static string GroupManagementView_Title {
            get {
                return ResourceManager.GetString("GroupManagementView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change password ähnelt.
        /// </summary>
        internal static string LoginView_ChangePasswordButton_Content {
            get {
                return ResourceManager.GetString("LoginView_ChangePasswordButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Session ID ähnelt.
        /// </summary>
        internal static string LoginView_Label_SessionId {
            get {
                return ResourceManager.GetString("LoginView_Label_SessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LOGIN ähnelt.
        /// </summary>
        internal static string LoginView_LoginButton_Content {
            get {
                return ResourceManager.GetString("LoginView_LoginButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die YOUR PASSWORD ähnelt.
        /// </summary>
        internal static string LoginView_OmniTextBox_Password_Watermark {
            get {
                return ResourceManager.GetString("LoginView_OmniTextBox_Password_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die YOUR USERNAME ähnelt.
        /// </summary>
        internal static string LoginView_OmniTextBox_Username_Watermark {
            get {
                return ResourceManager.GetString("LoginView_OmniTextBox_Username_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please log in. ähnelt.
        /// </summary>
        internal static string LoginView_Title_Content {
            get {
                return ResourceManager.GetString("LoginView_Title_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change password ähnelt.
        /// </summary>
        internal static string PasswordDialogView_HeadingLabel_Content {
            get {
                return ResourceManager.GetString("PasswordDialogView_HeadingLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New password ähnelt.
        /// </summary>
        internal static string PasswordDialogView_NewPasswordLabel_Content {
            get {
                return ResourceManager.GetString("PasswordDialogView_NewPasswordLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change password ähnelt.
        /// </summary>
        internal static string PasswordDialogView_OkButton_Content {
            get {
                return ResourceManager.GetString("PasswordDialogView_OkButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Old password ähnelt.
        /// </summary>
        internal static string PasswordDialogView_PasswordLabel_Content {
            get {
                return ResourceManager.GetString("PasswordDialogView_PasswordLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repeat new password ähnelt.
        /// </summary>
        internal static string PasswordDialogView_RepeatPasswordLabel_Content {
            get {
                return ResourceManager.GetString("PasswordDialogView_RepeatPasswordLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is already a user with name &apos;{0}&apos;.
        ///
        ///User creation aborted. ähnelt.
        /// </summary>
        internal static string UserAlreadyExistsDialog_Content {
            get {
                return ResourceManager.GetString("UserAlreadyExistsDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User already exists ähnelt.
        /// </summary>
        internal static string UserAlreadyExistsDialog_Title {
            get {
                return ResourceManager.GetString("UserAlreadyExistsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User ähnelt.
        /// </summary>
        internal static string UserManagementView_Button_Toggle {
            get {
                return ResourceManager.GetString("UserManagementView_Button_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Firstname ähnelt.
        /// </summary>
        internal static string UserManagementView_TableHeader_FirstName {
            get {
                return ResourceManager.GetString("UserManagementView_TableHeader_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string UserManagementView_TableHeader_Language {
            get {
                return ResourceManager.GetString("UserManagementView_TableHeader_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lastname ähnelt.
        /// </summary>
        internal static string UserManagementView_TableHeader_LastName {
            get {
                return ResourceManager.GetString("UserManagementView_TableHeader_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Role ähnelt.
        /// </summary>
        internal static string UserManagementView_TableHeader_Role {
            get {
                return ResourceManager.GetString("UserManagementView_TableHeader_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        internal static string UserManagementView_TableHeader_UserName {
            get {
                return ResourceManager.GetString("UserManagementView_TableHeader_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Management ähnelt.
        /// </summary>
        internal static string UserManagementView_Title {
            get {
                return ResourceManager.GetString("UserManagementView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logout ähnelt.
        /// </summary>
        internal static string UserMenu_Button_Logout {
            get {
                return ResourceManager.GetString("UserMenu_Button_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Management ähnelt.
        /// </summary>
        internal static string UserMenu_Button_UserManagement {
            get {
                return ResourceManager.GetString("UserMenu_Button_UserManagement", resourceCulture);
            }
        }
    }
}
