//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLS.Casy.Ui.Authorization.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings_de_DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLS.Casy.Ui.Authorization.Assets.Resources.ApplicationStrings_de-DE", typeof(ApplicationStrings_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Sprachumstellung wird erst nach dem Neustart der Anwendung wirksam ähnelt.
        /// </summary>
        internal static string ChangeLanguageInfo_Content {
            get {
                return ResourceManager.GetString("ChangeLanguageInfo_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neustart der Software notwendig ähnelt.
        /// </summary>
        internal static string ChangeLanguageInfo_Title {
            get {
                return ResourceManager.GetString("ChangeLanguageInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie sind dabei den Benutzer &apos;{0}&apos; zu löschen. Bitte bestätigen, dass Sie fortfahren wollen? ähnelt.
        /// </summary>
        internal static string DeleteUsersDialog_Content {
            get {
                return ResourceManager.GetString("DeleteUsersDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzer löschen ähnelt.
        /// </summary>
        internal static string DeleteUsersDialog_Title {
            get {
                return ResourceManager.GetString("DeleteUsersDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzergruppen ähnelt.
        /// </summary>
        internal static string GroupManagementView_Button_Toggle {
            get {
                return ResourceManager.GetString("GroupManagementView_Button_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzergruppenverwaltung ähnelt.
        /// </summary>
        internal static string GroupManagementView_Title {
            get {
                return ResourceManager.GetString("GroupManagementView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ändern ähnelt.
        /// </summary>
        internal static string LoginView_ChangePasswordButton_Content {
            get {
                return ResourceManager.GetString("LoginView_ChangePasswordButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Session ID ähnelt.
        /// </summary>
        internal static string LoginView_Label_SessionId {
            get {
                return ResourceManager.GetString("LoginView_Label_SessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ANMELDEN ähnelt.
        /// </summary>
        internal static string LoginView_LoginButton_Content {
            get {
                return ResourceManager.GetString("LoginView_LoginButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IHR PASSWORT ähnelt.
        /// </summary>
        internal static string LoginView_OmniTextBox_Password_Watermark {
            get {
                return ResourceManager.GetString("LoginView_OmniTextBox_Password_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IHR BENUTZERNAME ähnelt.
        /// </summary>
        internal static string LoginView_OmniTextBox_Username_Watermark {
            get {
                return ResourceManager.GetString("LoginView_OmniTextBox_Username_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte melden Sie sich an. ähnelt.
        /// </summary>
        internal static string LoginView_Title_Content {
            get {
                return ResourceManager.GetString("LoginView_Title_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ändern ähnelt.
        /// </summary>
        internal static string PasswordDialogView_HeadingLabel_Content {
            get {
                return ResourceManager.GetString("PasswordDialogView_HeadingLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Passwort ähnelt.
        /// </summary>
        internal static string PasswordDialogView_NewPasswordLabel_Content {
            get {
                return ResourceManager.GetString("PasswordDialogView_NewPasswordLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ändern ähnelt.
        /// </summary>
        internal static string PasswordDialogView_OkButton_Content {
            get {
                return ResourceManager.GetString("PasswordDialogView_OkButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Altes Passwort ähnelt.
        /// </summary>
        internal static string PasswordDialogView_PasswordLabel_Content {
            get {
                return ResourceManager.GetString("PasswordDialogView_PasswordLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Passwort wiederholen ähnelt.
        /// </summary>
        internal static string PasswordDialogView_RepeatPasswordLabel_Content {
            get {
                return ResourceManager.GetString("PasswordDialogView_RepeatPasswordLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Benutzer mit dem Benuternamen &apos;{0}&apos; existiert bereits.
        ///
        ///Benutzererstellung abgebrochen. ähnelt.
        /// </summary>
        internal static string UserAlreadyExistsDialog_Content {
            get {
                return ResourceManager.GetString("UserAlreadyExistsDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzername existiert bereits ähnelt.
        /// </summary>
        internal static string UserAlreadyExistsDialog_Title {
            get {
                return ResourceManager.GetString("UserAlreadyExistsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzer ähnelt.
        /// </summary>
        internal static string UserManagementView_Button_Toggle {
            get {
                return ResourceManager.GetString("UserManagementView_Button_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorname ähnelt.
        /// </summary>
        internal static string UserManagementView_TableHeader_FirstName {
            get {
                return ResourceManager.GetString("UserManagementView_TableHeader_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        internal static string UserManagementView_TableHeader_Language {
            get {
                return ResourceManager.GetString("UserManagementView_TableHeader_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nachname ähnelt.
        /// </summary>
        internal static string UserManagementView_TableHeader_LastName {
            get {
                return ResourceManager.GetString("UserManagementView_TableHeader_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolle ähnelt.
        /// </summary>
        internal static string UserManagementView_TableHeader_Role {
            get {
                return ResourceManager.GetString("UserManagementView_TableHeader_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzername ähnelt.
        /// </summary>
        internal static string UserManagementView_TableHeader_UserName {
            get {
                return ResourceManager.GetString("UserManagementView_TableHeader_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzerverwaltung ähnelt.
        /// </summary>
        internal static string UserManagementView_Title {
            get {
                return ResourceManager.GetString("UserManagementView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abmelden ähnelt.
        /// </summary>
        internal static string UserMenu_Button_Logout {
            get {
                return ResourceManager.GetString("UserMenu_Button_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzerverwaltung ähnelt.
        /// </summary>
        internal static string UserMenu_Button_UserManagement {
            get {
                return ResourceManager.GetString("UserMenu_Button_UserManagement", resourceCulture);
            }
        }
    }
}
