//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLS.Casy.Ui.AuditTrail.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings_en_US() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLS.Casy.Ui.AuditTrail.Assets.Resources.ApplicationStrings_en-US", typeof(ApplicationStrings_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Added ähnelt.
        /// </summary>
        internal static string AuditTrailEntry_Action_Added {
            get {
                return ResourceManager.GetString("AuditTrailEntry_Action_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deleted ähnelt.
        /// </summary>
        internal static string AuditTrailEntry_Action_Deleted {
            get {
                return ResourceManager.GetString("AuditTrailEntry_Action_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modified ähnelt.
        /// </summary>
        internal static string AuditTrailEntry_Action_Modified {
            get {
                return ResourceManager.GetString("AuditTrailEntry_Action_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measurement ähnelt.
        /// </summary>
        internal static string AuditTrailEntry_Name_Measurement {
            get {
                return ResourceManager.GetString("AuditTrailEntry_Name_Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measurement Data ähnelt.
        /// </summary>
        internal static string AuditTrailEntry_Name_MeasurementData {
            get {
                return ResourceManager.GetString("AuditTrailEntry_Name_MeasurementData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Range ähnelt.
        /// </summary>
        internal static string AuditTrailEntry_Name_Range {
            get {
                return ResourceManager.GetString("AuditTrailEntry_Name_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template ähnelt.
        /// </summary>
        internal static string AuditTrailEntry_Name_Template {
            get {
                return ResourceManager.GetString("AuditTrailEntry_Name_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action ähnelt.
        /// </summary>
        internal static string AuditTrailView_GridColum_Action {
            get {
                return ResourceManager.GetString("AuditTrailView_GridColum_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Computer Name ähnelt.
        /// </summary>
        internal static string AuditTrailView_GridColum_ComputerName {
            get {
                return ResourceManager.GetString("AuditTrailView_GridColum_ComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Object ähnelt.
        /// </summary>
        internal static string AuditTrailView_GridColum_EntityName {
            get {
                return ResourceManager.GetString("AuditTrailView_GridColum_EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measurement Result ähnelt.
        /// </summary>
        internal static string AuditTrailView_GridColum_MeasureResultName {
            get {
                return ResourceManager.GetString("AuditTrailView_GridColum_MeasureResultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        internal static string AuditTrailView_GridColum_NewValue {
            get {
                return ResourceManager.GetString("AuditTrailView_GridColum_NewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous ähnelt.
        /// </summary>
        internal static string AuditTrailView_GridColum_OldValue {
            get {
                return ResourceManager.GetString("AuditTrailView_GridColum_OldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entity Primary Key ähnelt.
        /// </summary>
        internal static string AuditTrailView_GridColum_PrimaryKeyValue {
            get {
                return ResourceManager.GetString("AuditTrailView_GridColum_PrimaryKeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Property ähnelt.
        /// </summary>
        internal static string AuditTrailView_GridColum_PropertyName {
            get {
                return ResourceManager.GetString("AuditTrailView_GridColum_PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Software Version ähnelt.
        /// </summary>
        internal static string AuditTrailView_GridColum_SoftwareVersion {
            get {
                return ResourceManager.GetString("AuditTrailView_GridColum_SoftwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timestamp (UTC) ähnelt.
        /// </summary>
        internal static string AuditTrailView_GridColum_Timestamp {
            get {
                return ResourceManager.GetString("AuditTrailView_GridColum_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User ähnelt.
        /// </summary>
        internal static string AuditTrailView_GridColum_User {
            get {
                return ResourceManager.GetString("AuditTrailView_GridColum_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audit Trail ähnelt.
        /// </summary>
        internal static string AuditTrailView_Title {
            get {
                return ResourceManager.GetString("AuditTrailView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter: ähnelt.
        /// </summary>
        internal static string SystemLogView_Filter_Label {
            get {
                return ResourceManager.GetString("SystemLogView_Filter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category ähnelt.
        /// </summary>
        internal static string SystemLogView_GridColum_Category {
            get {
                return ResourceManager.GetString("SystemLogView_GridColum_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timestamp (UTC) ähnelt.
        /// </summary>
        internal static string SystemLogView_GridColum_Date {
            get {
                return ResourceManager.GetString("SystemLogView_GridColum_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        internal static string SystemLogView_GridColum_Level {
            get {
                return ResourceManager.GetString("SystemLogView_GridColum_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message ähnelt.
        /// </summary>
        internal static string SystemLogView_GridColum_Message {
            get {
                return ResourceManager.GetString("SystemLogView_GridColum_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User ähnelt.
        /// </summary>
        internal static string SystemLogView_GridColum_User {
            get {
                return ResourceManager.GetString("SystemLogView_GridColum_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System Log ähnelt.
        /// </summary>
        internal static string SystemLogView_Title {
            get {
                return ResourceManager.GetString("SystemLogView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System Log ähnelt.
        /// </summary>
        internal static string UserMenu_Button_SystemLog {
            get {
                return ResourceManager.GetString("UserMenu_Button_SystemLog", resourceCulture);
            }
        }
    }
}
