//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLS.Casy.Core.Update.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings_en_US() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLS.Casy.Core.Update.Assets.Resources.ApplicationStrings_en-US", typeof(ApplicationStrings_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ähnelt.
        /// </summary>
        internal static string ProgressBox_OnlineUpdate_Message {
            get {
                return ResourceManager.GetString("ProgressBox_OnlineUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading update {0}… ähnelt.
        /// </summary>
        internal static string ProgressBox_OnlineUpdate_Message_Downloading {
            get {
                return ResourceManager.GetString("ProgressBox_OnlineUpdate_Message_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extracting update data  ... ähnelt.
        /// </summary>
        internal static string ProgressBox_OnlineUpdate_Message_Extracting {
            get {
                return ResourceManager.GetString("ProgressBox_OnlineUpdate_Message_Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shutting down application and starting update ... ähnelt.
        /// </summary>
        internal static string ProgressBox_OnlineUpdate_Message_ShutingDown {
            get {
                return ResourceManager.GetString("ProgressBox_OnlineUpdate_Message_ShutingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Online Software Update ähnelt.
        /// </summary>
        internal static string ProgressBox_OnlineUpdate_Title {
            get {
                return ResourceManager.GetString("ProgressBox_OnlineUpdate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ähnelt.
        /// </summary>
        internal static string ProgressBox_UsbUpdate_Message {
            get {
                return ResourceManager.GetString("ProgressBox_UsbUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extracting update data  ... ähnelt.
        /// </summary>
        internal static string ProgressBox_UsbUpdate_Message_Extracting {
            get {
                return ResourceManager.GetString("ProgressBox_UsbUpdate_Message_Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shutting down application and starting update ... ähnelt.
        /// </summary>
        internal static string ProgressBox_UsbUpdate_Message_ShutingDown {
            get {
                return ResourceManager.GetString("ProgressBox_UsbUpdate_Message_ShutingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Software Update from USB device ähnelt.
        /// </summary>
        internal static string ProgressBox_UsbUpdate_Title {
            get {
                return ResourceManager.GetString("ProgressBox_UsbUpdate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Software update detected. Do you want to update the current software version &apos;{0}&apos; by the new version &apos;{1}&apos;? ähnelt.
        /// </summary>
        internal static string UpdateDialog_Content {
            get {
                return ResourceManager.GetString("UpdateDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Software update detected. Do you want to update the current software version &apos;{0}&apos; by the new version &apos;{1}&apos;?
        ///NOTICE: Probably it will be neccessary to perform an additional, incremental update after the software has been restarted. ähnelt.
        /// </summary>
        internal static string UpdateDialog_Content_Incremental {
            get {
                return ResourceManager.GetString("UpdateDialog_Content_Incremental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Software Update ähnelt.
        /// </summary>
        internal static string UpdateDialog_Title {
            get {
                return ResourceManager.GetString("UpdateDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Easter / Corona Update for all users of NEW CASY
        ///Updated Version 1.0.2.2
        ///
        ///The new CASY Software has seen many improvements and new features like START UP and SHUT DOWN Wizard.
        ///The update to version 1.0.2.2 is free for all New CASY users and introduces a new feature requested by many users:
        ///• “Print all“ with a single click (printing icon in the top menu, which allows to create PDF of all open measurements)
        ///Additionally the version brings several bug fixes and stability improvements.
        ///We recommend all  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string UpdateService_ReleaseNodes_Message {
            get {
                return ResourceManager.GetString("UpdateService_ReleaseNodes_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We installed an update for you ähnelt.
        /// </summary>
        internal static string UpdateService_ReleaseNodes_Title {
            get {
                return ResourceManager.GetString("UpdateService_ReleaseNodes_Title", resourceCulture);
            }
        }
    }
}
